### ISSUE TITLE
SSTP: Win7 and TLS 1.0

### ISSUE THREAD

**Issue by andrewfer000** [SoftEtherVPN/SoftEtherVPN#1423] opened 2021-07-10 18:29 UTC
This is a continued conversion from the EAP-MSCHAPv2 PR (#1420)

**Comment by andrewfer000** [comment] 2021-07-10 18:32
As we already discussed, Windows 7 (and likely Vista too), Windows 8, and maybe Windows 8.1 (not tested) do not support SSTP over TLS 1.2

**Comment by andrewfer000** [comment] 2021-07-10 18:40
I compiled SoftEther_Stable from the stable branch and it seems that TLS-1.0 is enabled. Meaning it's not OpenSSL on my Ubuntu 20.04 machine.

**Comment by andrewfer000** [comment] 2021-07-10 18:59
Also while I thought the same issue was occurring on Open SSTP Client on Android, that is not the case since Open SSTP Client seemed to fix itself out of the blue... Also it supports TLS 1.2

**Comment by metalefty** [comment] 2021-07-11 03:41
What about TLS 1.1.?

**Comment by andrewfer000** [comment] 2021-07-11 04:28
SoftEther 5.x only supports TLS 1.2. TLS 1.0 and 1.1 are not available. On 4.x versions they are all together.

**Comment by metalefty** [comment] 2021-07-11 06:01
I meant does Win 7 support TLS1.1 SSTP?

**Comment by andrewfer000** [comment] 2021-07-11 06:13
Not sure. I cant get TLS 1.1 by itself. Windows 7 supports TLS 1.0, 1.1, and 1.2 in Internet Options but that does not change anything with SSTP.

**Comment by andrewfer000** [comment] 2021-07-11 07:14
https://social.technet.microsoft.com/Forums/windows/en-US/8db7cb80-5812-4582-bec2-293525bbd7a5/windows-7-sstp-over-tls-11tls-12?forum=w7itpronetworking

Seems that SSTP on Windows 7 needs to be in TLS 1.0. Should we try in re-enable TLS 1.0 in SoftEther like the 4.x version or should we drop support for it and move on. L2TP/IPsec still works on Win 7. 

@domosekai seems to have the latest version of 5.x still working with TLS 1.0/1.1 which I find very strange. What is it with his configuration that makes it so even the latest version work with TLS 1.0? 

Like I said before, even with my Ubuntu 20.04 machine and modern version of OpenSSL I can still compile SE 4.x from the Stable branch with support for TLS 1.0/1.1. Is there a setting in the make file to change what versions of TLS are enabled by SoftEther when using a newer version of OpenSSL?

**Comment by domosekai** [comment] 2021-07-12 17:08
Just a few facts.
1. Win 7 does have TLS 1.2 support in SSTP, but not from the earliest version. My build number is 7601.24214 and it works with TLS 1.2 out of the box.
2. The stable version that is downloadable from SoftEther official site (where you can choose a particular OS and CPU type) is in binary form. (You still need to make it but it's binary, not source.) It is different from the open source version and it has Openssl statically linked with TLS 1.0 support.
3. In the source code from both stable 4.x and developer 5.x branch, there is no restriction with regard to TLS versions. The version you can actually use depends on the openssl library installed on the server. Debian 10 and Ubuntu 20.04 has disabled TLS 1.0/1.1.

**Comment by andrewfer000** [comment] 2021-07-12 18:41
1. Yes I assumed that. I'm sure versions of Windows 7 that are kept up to date will support it with SSTP.

2. I never download from softether.org, my version of 4.x is built from Source from the stable repo on Github.

3. I'm aware of that based on my configuration file but I wasn't sure if it was something with options in the make file.

@domosekai Can you do me a favor and upload your (vpnserver) binary here so I can see if that solves anything. Just put it in a zip file. I don't need anything else. I'll just drop it in as my current binary.

**Comment by chipitsine** [comment] 2021-07-12 19:14
for the record.

I took Ubuntu 20.04

I built SE Stable from source (no static link), it listens for TLS1.0 ... TLS1.2
I built SE Developer edition from source (including commits from 2019 .. 2018 ... ), it listens for TLS1.2

I'll do more investigations later. It definetly looks like openssl configuration (overriden by SE Stable)

**Comment by domosekai** [comment] 2021-07-13 02:53
Sorry, I should not say Ubuntu 20.04. I only used Debian 10 and it is very likely ubuntu is different.

**Comment by davidebeatrici** [comment] 2021-07-13 03:21
https://packages.debian.org/buster/openssl (Debian 10): [openssl.cnf](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6805650/openssl.cnf.txt)

https://packages.ubuntu.com/focal-updates/openssl (Ubuntu 20.04): [openssl.cnf](https://github.com/SoftEtherVPN/SoftEtherVPN/files/6805659/openssl.cnf.txt)

**Comment by andrewfer000** [comment] 2021-07-13 04:50
I got TLS 1.0 back on SoftEther 5.x on Ubuntu 20.04 by adding this to the top of `/etc/ssl/openssl.cnf`

```
openssl_conf = default_conf

[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=1
```

**Comment by domosekai** [comment] 2021-07-13 04:55
Stable branch does override the openssl config onsite.

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/ddc99f085fd6c54feaf4e41912bc8ab5903bdf8e/src/Mayaqua/Network.c#L18175-L18181

In developer branch we have an option for this so user can opt in for old versions.
```
bool Override_Security_Level false
uint Override_Security_Level_Value 0
```

**Comment by andrewfer000** [comment] 2021-07-13 04:57
> Stable branch does override the openssl config onsite.
> 
> https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/ddc99f085fd6c54feaf4e41912bc8ab5903bdf8e/src/Mayaqua/Network.c#L18175-L18181
> 
> In developer branch we have an option for this so user can opt in for old versions.
> 
> ```
> bool Override_Security_Level false
> uint Override_Security_Level_Value 0
> ```

Lol you came just as I figured out another solution. I think the one you put is better. Did you test it?

**Comment by domosekai** [comment] 2021-07-13 05:09
I must point out that the override of security level is not enough in Debian, due to different approaches taken by Debian and Ubuntu. I am not sure about other distros.

Ubuntu sets default security level to 2 at build time. (see `-DOPENSSL_TLS_SECURITY_LEVEL=2`)
```
# openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed May  5 00:13:30 2021 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-5wtPyT/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

Debian does not change the security level at build time but impose the limitation in openssl.cnf.
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```

The overriding approach we are taking in stable branch (enforced by code) or in developer branch (when user opted in) only changes the security level. So it should work in Ubuntu (assumed) but not in Debian (confirmed) where `MinProtocol` is also set.

**Comment by domosekai** [comment] 2021-07-13 07:04
I must admit this issue is far more complicated than I first thought.

First, we must know that the approaches taken by Debian and Ubuntu to enforce TLS 1.2+ are different. I am not sure about other distros yet.

Ubuntu sets security level to 2 at build time. (see `-DOPENSSL_TLS_SECURITY_LEVEL=2` below)
```
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed Apr 28 00:37:28 2021 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-olnknv/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

However, according to Openssl docs, security level 2 **DOES NOT** disable versions below 1.2.
> Level 2
> Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited. In addition to the level 1 exclusions any ciphersuite using RC4 is also prohibited. **SSL version 3 is also not allowed.** Compression is disabled.
https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_security_level.html

I have tested in Debian 10. If security level is 2, TLS 1.0 still connects. So this is a Ubuntu thing.

Ubuntu manpage:
> Level 2
> Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited.  In addition to the level 1 exclusions any cipher suite using RC4 is also prohibited. **On Ubuntu, TLS versions below 1.2 are not permitted.** Compression is disabled.
https://manpages.ubuntu.com/manpages/focal/man3/SSL_CTX_set_security_level.3ssl.html

OK. Let's see Debian 10.
Debian (probably) does not change the Openssl source. Instead it sets min protocol version to 1.2 in openssl.cnf.
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```

Therefore, our current approach of resetting security level (either fixed in code as in stable branch or if user opts in as in developer branch) in order to restore TLS 1.0/1.1 support **ONLY WORKS ON UBUNTU** because the thing is a Ubuntu "hack".

**Comment by domosekai** [comment] 2021-07-13 12:19
CentOS 8 also enforces TLS 1.2 and its approach is similar to Debian 10, i.e. by setting `MinProtocol` in openssl.cnf.
```
CipherString = @SECLEVEL=2:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
MinProtocol = TLSv1.2
MaxProtocol = TLSv1.3
SignatureAlgorithms = ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ed25519:ed448:rsa_pss_pss_sha256:rsa_pss_rsae_sha256:rsa_pss_pss_sha384:rsa_pss_rsae_sha384:rsa_pss_pss_sha512:rsa_pss_rsae_sha512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1
```

Therefore the security level trick to support TLS 1.0 only works on Ubuntu.

By the way, the reason of adding the `Override_Security_Level` option was not for compatibility with TLS 1.0/1.1, but for the old 1024-bit key size generated on old SE servers. Security level 2 requires 2048 bits. See #1101 .

**Comment by domosekai** [comment] 2021-07-13 13:59
Fedora 34 configuration is identical to CentOS 8.

**Comment by andrewfer000** [comment] 2021-07-13 18:11
I'm not much of a CentOS guy but once my VPS provider incorperates RockyLinux and/or AlmaLinux on the service I'll test then.

**Comment by takotakot** [comment] 2021-07-14 14:13
@domosekai Thank you for calling.

The reason why I created #1101 is that SE did not work on CentOS 8.
At first I run `check` and that failed.

I tested with editing `/etc/crypto-policies/back-ends/opensslcnf.config` and `/etc/pki/tls/openssl.cnf` like 
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1423#issuecomment-878777216 and https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1423#issuecomment-878833693.
Then I thought that it might be the problem on only security level.
(I'm not good at both SE and OpenSSL.)

> the reason of adding the Override_Security_Level option was not for compatibility with TLS 1.0/1.1

I agree (I didn't think of compatibility at the time). I'm sorry for confusing you.
If I was on the wrong way, please correct it.

Using static (self) build of openssl or using Docker may help because packaged openssl is "far more complicated."

**Comment by domosekai** [comment] 2021-07-14 15:42
@takotakot Thank you for your reply. At first I thought your patch was meant to restore connectivity via TLS 1.0/1.1 and I was wrong. It's still a useful option. But the problem is, we had better tell user when and how to use that option.
And your reply just made me come up with one idea, that is to add protocol stack checks in the `check` command.

Currently `check` looks like this.
```
Checking 'Kernel System'...
              Pass
Checking 'Memory Operation System'...
              Pass
Checking 'ANSI / Unicode string processing system'...
              Pass
Checking 'File system'...
              Pass
Checking 'Thread processing system'...
              Pass
Checking 'Network system'...
              Pass

All checks passed. It is most likely that SoftEther VPN Server / Bridge can operate normally on this system.
```

We can add checks for IPv4/IPv6, TLS 1.0-1.3 etc.. If TLS 1.0 and 1.1 failed but not disabled in the config file, we retrieve openssl config from the system and tell user your system has a hardened TLS environment, and the way to restore compatibility with legacy devices.

**Comment by takotakot** [comment] 2021-07-14 16:11
> we had better tell user when and how to use that option.

Definitely yes.

>  add protocol stack checks in the `check`
> ... tell user your system has a hardened TLS environment

That sounds very helpful. Many users don't know much about protocol stacks and library options.
The new checks will show us the points to consider and what to do.

**Comment by beavermml** [comment] 2021-07-22 09:30
im pretty sure the issue lies with the built in SSTP client it self.. it seems that it will try to use TLS1.0 anyway..
and in latest Win10 insider and Win11, the bult in SSTP client wont negotiate TLS1.0 at all

**Comment by lixh1223** [comment] 2022-07-13 07:33
CentOS7版视频安装教程：https://youtu.be/fWGw6Qdh1pY
Windows版视频安装教程：https://youtu.be/lXb7FxxEcE0

**Closed** 2023-01-08 13:37 UTC
