### ISSUE TITLE
CLI - when arguments are optional, they should not reset their value to default

### ISSUE THREAD

**Issue by shakibamoshiri** [SoftEtherVPN/SoftEtherVPN#1787] opened 2023-03-01 08:43 UTC
### Prerequisites

* [X] Can you reproduce?
* [X] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
both stable and developer 

### Description
Using both RPC-JSON API and vpncmd if an option is omitted, omitted ones will be reset to default. So if you want to set "NOTE" for a user we have to set all options again

```bash
Usage:
  UserSet [name] [/GROUP:group] [/REALNAME:realname] [/NOTE:note]
```
I cannot recall any CLIs has this behavior. When arguments are optional, they should not reset their value to default while those values have been set already.

**Expected behavior:**
When arguments are optional, they should not reset their value to default while those values have been set already.

**Actual behavior:**
Values are set to default. Usually empty, false, 0, etc  
Here is #1730 more about `SetUser` via RPC-JSON API I described

### Steps to reproduce

1. create a user and specify "real name", "note", "group"
2. try `UserSet` via vpncmd or `SetUser` via RPC-JSON API only set one options

**Comment by domosekai** [comment] 2023-03-01 10:11
Duplicate of #1730 which is also created by you.
Please close the either one.

**Closed** 2023-03-01 10:40 UTC
