### ISSUE TITLE
regression introduced in PR#1321 (Linux)

### ISSUE THREAD

**Issue by chipitsine** [SoftEtherVPN/SoftEtherVPN#1328] opened 2021-04-17 10:48 UTC
during openvpn live testing we perform the following setup

```
./vpncmd 127.0.0.1:443 /SERVER /HUB:DEFAULT /CMD:SecureNatEnable
./vpncmd 127.0.0.1:443 /SERVER /CMD:"ProtoOptionsSet OpenVPN /NAME:Enabled /VALUE:True"
./vpncmd 127.0.0.1:443 /SERVER /CMD:"PortsUDPSet 1194"
./vpncmd 127.0.0.1:443 /SERVER /HUB:DEFAULT /CMD:"UserCreate test /GROUP:none /REALNAME:none /NOTE:none"
./vpncmd 127.0.0.1:443 /SERVER /HUB:DEFAULT /CMD:"UserPasswordSet test /PASSWORD:test"
./vpncmd 127.0.0.1:443 /SERVER /CMD:"OpenVpnMakeConfig my_openvpn_config.zip"
```

before PR#1321:

```
[root@localhost SoftEtherVPN-master]# netstat -lpn | grep vpnserver
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      59363/vpnserver     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      59363/vpnserver     
tcp        0      0 0.0.0.0:992             0.0.0.0:*               LISTEN      59363/vpnserver     
tcp        0      0 0.0.0.0:1194            0.0.0.0:*               LISTEN      59363/vpnserver     
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           59363/vpnserver     
udp        0      0 0.0.0.0:48706           0.0.0.0:*                           59363/vpnserver     
udp        0      0 0.0.0.0:28926           0.0.0.0:*                           59363/vpnserver     
raw        0      0 0.0.0.0:1               0.0.0.0:*               7           59363/vpnserver     
raw        0      0 0.0.0.0:6               0.0.0.0:*               7           59363/vpnserver     
raw        0      0 0.0.0.0:17              0.0.0.0:*               7           59363/vpnserver     
[root@localhost SoftEtherVPN-master]# 
```

after PR#1321:

```
[root@localhost SoftEtherVPN-master]# netstat -lpn | grep vpnserver
tcp        0      0 0.0.0.0:5555            0.0.0.0:*               LISTEN      58325/vpnserver     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      58325/vpnserver     
tcp        0      0 0.0.0.0:992             0.0.0.0:*               LISTEN      58325/vpnserver     
tcp        0      0 0.0.0.0:1194            0.0.0.0:*               LISTEN      58325/vpnserver     
udp6       0      0 :::1194                 :::*                                58325/vpnserver     
[root@localhost SoftEtherVPN-master]# 
```

**Comment by chipitsine** [comment] 2021-04-17 10:55
@metalefty , btw, can you check on FreeBSD ?

**Comment by davidebeatrici** [comment] 2021-04-17 18:35
The issue appeared after #1321 was merged, but the cause is the `ListenIP` setting.

More specifically, the default value is composed entirely by zeroes. The old format treated such an address as `0.0.0.0`, while the new one treats it as `::`.

As a workaround we can call `ZeroIP4()` for the variable, so that the previous behavior is retained.

However, the real solution would be to make `ListenIP` a list and add two default entries: `::` and `0.0.0.0`.

**Comment by metalefty** [comment] 2021-04-20 06:38
Hi,

@chipitsine  regarding the check on FreeBSD, I'll have a look when I have some time.

@davidebeatrici  BTW, `ListenIP` has some bugs as I reported at #1308, #1309.

**Comment by metalefty** [comment] 2021-04-20 06:38
Hi,

@chipitsine  regarding the check on FreeBSD, I'll have a look when I have some time.

@davidebeatrici  BTW, `ListenIP` has some bugs as I reported at #1308, #1309.

**Comment by chipitsine** [comment] 2021-04-20 06:58
I also think it makes sense to check on FreeBSD in "ipv4 only" and "ipv4 + ipv6" if possible.

I'll try to check myself this week

**Comment by chipitsine** [comment] 2021-04-20 07:17
it's a pity that we do not have automation to catch those bugs :(

**Comment by davidebeatrici** [comment] 2021-04-20 18:18
@metalefty I deleted the duplicate comment.

The two bugs you reported indeed explain the current behavior.

**Closed** 2021-07-07 11:08 UTC
