### ISSUE TITLE
Radius user accounting

### ISSUE THREAD

**Issue by liam-prog** [SoftEtherVPN/SoftEtherVPN#1626] opened 2022-07-18 07:58 UTC
Hi, there!

Thank you for using SoftEther.

---

### Prerequisites

* [ ] Can you reproduce?
* [ ] Are you running the latest version of SoftEtherVPN? Yes

Please add a feature to manage user sessions (max sessions or current user session) with radius

**Comment by metalefty** [comment] 2022-07-19 07:50
Duplicate of #101.

**Closed** 2022-07-19 17:27 UTC
