### ISSUE TITLE
SSTP: document setup process for Windows

### ISSUE THREAD

**Issue by davidebeatrici** [SoftEtherVPN/SoftEtherVPN#1169] opened 2020-07-09 19:43 UTC
@Evengard Could you take a look, please?

```
LOG: On the TCP Listener (Port 443), a Client (IP address 192.168.122.100, Host name "DEV", Port number 49706) has connected.
LOG: For the client (IP address: 192.168.122.100, host name: "DEV", port number: 49706), connection "CID-2" has been created.
ProtoImplDetect(): unrecognized protocol
LOG: SSL communication for connection "CID-2" has been started. The encryption algorithm name is "ECDHE-RSA-AES256-GCM-SHA384".
Downloading Signature...
ProcessSstpHttps Start.
SSTP Control Packet Recv: Msg = 1, Num = 1
SSTP Control Packet Send: Msg = 2, Num = 1
PPP InitializeMsChapV2_UseDoubleMsChapV2 = 0x0
PPP Link establishment phase
LOG: SSTP PPP Session [192.168.122.100:49706]: A new PPP session (Upper protocol: SSTP) is started. IP Address of PPP Client: 192.168.122.100 (Hostname: "DEV"), Port Number of PPP Client: 49706, IP Address of PPP Server: 192.168.122.1, Port Number of PPP Server: 443, Client Software Name: "Microsoft SSTP VPN Client", IPv4 TCP MSS (Max Segment Size): 0 bytes
PPP starting main dataloop
Got LCP packet request ID=0 OptionsListSize=5
Unsupported LCP option = 0x5
Unsupported LCP option = 0x7
Unsupported LCP option = 0x8
Unsupported LCP option = 0xd
Rejected LCP option = 0x5, proto = 0xc021
Rejected LCP option = 0x7, proto = 0xc021
Rejected LCP option = 0x8, proto = 0xc021
Rejected LCP option = 0xd, proto = 0xc021
Rejected LCP options...
Request EAP
Got LCP packet request ID=1 OptionsListSize=1
NACKed LCP option = 0x1, proto = 0xc021
NACKed LCP options...
Setting BEFORE_AUTH from ACK on LCP response parse on EAP accept
Got LCP packet request ID=2 OptionsListSize=1
ACKed LCP option = 0x1, proto = 0xc021
src/Cedar/Proto_PPP.c: 109
src/Cedar/Proto_PPP.c: 109
src/Cedar/Proto_PPP.c: 109
Got a EAP_NAK, abandoning EAP protocol
Rejecting PPP protocol = 0xc227
Request MSCHAPv2 from EAP NAK
SSTP Control Packet Recv: Msg = 6, Num = 1
SSTP Control Packet Send: Msg = 7, Num = 0
LOG: SSTP PPP Session [192.168.122.100:49706]: The PPP session is disconnected because the upper-layer protocol "SSTP" has been disconnected.
Exited main dataloop, status = 0x110
LOG: SSTP PPP Session [192.168.122.100:49706]: The PPP session is disconnected.
PPP Session ended correctly
ProcessSstpHttps End.
LOG: Connection "CID-2" terminated by the cause "Connection has been disconnected." (code 3).
ConnectionAccept(): ServerAccept() failed with error 3
src/Cedar/Connection.c 2990 c->flag1 == false
Connection CID-2 Deleted from Cedar.
LOG: Connection "CID-2" has been terminated.
src/Cedar/Listener.c 182 flag1 == false
LOG: The connection with the client (IP address 192.168.122.100, Port number 49706) has been disconnected.
```

**Comment by Evengard** [comment] 2020-07-09 21:19
I actually do know what is happening, and it is a bit tricky...
You see, EAP and all other auth mechanisms on Windows are not really compatible. And because EAP is a "preferred" authentication mechanism, although it is used only for the EAP-TLS aka auth via certificate mechanism, and Windows can't recover from it, we get a disconnect.
The problem is because at this point of time we have no way of filtering out EAP-TLS because we don't know yet the username of the user, so we can't check if he got a certificate or password auth.
This is easily fixed on client side by disabling EAP and setting MSCHAPv2 and/or PAP authentication.

**Comment by davidebeatrici** [comment] 2020-07-09 22:15
Thank you very much for the detailed explanation!

Disabling EAP indeed fixes the issue:
<img alt="SSTP security settings" src="https://user-images.githubusercontent.com/5897523/87096043-3e797a00-c242-11ea-8530-88164b8acb82.png">

We should probably document the behavior somewhere...

**Comment by metalefty** [comment] 2020-07-10 00:15
As far as I tried, default setup doesn't use EAP.

**Comment by davidebeatrici** [comment] 2020-07-10 00:29
Operating system?

**Comment by metalefty** [comment] 2020-07-10 00:44
Window 10 Pro 2004 build 19041.329. 

I've just confirmed SSTP defaults to MS-CHAPv2 like your screenshot.

**Comment by metalefty** [comment] 2020-07-10 00:53
I created a new SSTP setup from here:

![2020-07-10 (2)](https://user-images.githubusercontent.com/941609/87104411-cb4c2400-c292-11ea-9b3a-6af512c1340a.png)

and opened the property right after creation and once connected.
![2020-07-10 (1)](https://user-images.githubusercontent.com/941609/87104421-d30bc880-c292-11ea-8611-eba135ee7395.png)

**Comment by davidebeatrici** [comment] 2020-07-11 00:23
I tested the SSTP setup on Windows 10 1809, maybe the behavior was changed in a more recent version?

**Comment by Evengard** [comment] 2020-07-11 00:40
![изображение](https://user-images.githubusercontent.com/798735/87212586-fd5b9580-c327-11ea-9865-fb4e2b8aa963.png)
This is how it is when set up from scratch. It's a weird mode though - the radiobutton isn't set on either of the options. I honestly don't know how actually Windows handle this...

There might be a solution via implementing EAP-MSCHAPv2, but this is more like a workaround than an actual solution...

**Comment by davidebeatrici** [comment] 2020-07-11 17:42
Isn't forcing MS-CHAP v2 better anyway?

**Comment by Evengard** [comment] 2020-07-11 18:11
We might actually make MSCHAPv2 default, and then only falling back to EAP and then PAP, I guess, but I can't say that this won't break something when doing EAP-TLS auth with certificates before I test it...

**Closed** 2021-07-10 18:27 UTC
Labels: protocol/SSTP
