### ISSUE TITLE
Android binaries. needed so much!

### ISSUE THREAD

**Issue by DI555** [SoftEtherVPN/SoftEtherVPN#1105] opened 2020-04-26 14:35 UTC
Please provide and Android binaries too. Client, server and bridge builds would be awesome!
Since i found linux binaries here:
github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases
Great to be and Android binaries be there also!
Many thanks in advance!

**Comment by drkrool** [comment] 2020-05-25 06:03
Android client would be godsent

**Comment by chipitsine** [comment] 2020-05-25 15:12
not many PRs were seen on the subject

**Comment by DI555** [comment] 2020-11-10 05:58
yes, at least android client one could be greatest!
...because in other way we're using openvpn one which not so good as softethervpn(((

**Comment by domosekai** [comment] 2021-12-21 15:24
Duplicate of #1019

**Closed by domosekai** 2021-12-21 15:24 UTC
