### ISSUE TITLE
Radius does not work from second Hub

### ISSUE THREAD

**Issue by Delagen** [SoftEtherVPN/SoftEtherVPN#367] opened 2017-10-23 19:01 UTC
Tuned the same Radius Server for 2 Virtual Hub

When I connect via SSTP to default Hub using simple username ALL fine.
When I connect via SSTP to default Hub using username@hub I get Radius reject
When I connect via SSTP to second Hub using username@hub2 even request to Radius does not send.

Listened by tcpdump on Radius interface.

**Comment by arqteqnet** [comment] 2020-12-22 00:34
I've tested this and it works as expected with multiple hubs to same radius server.

**Comment by domosekai** [comment] 2023-02-25 14:40
You can try EAP if the radius server supports, with #1775 
It's hard to fix it with MSCHAPv2 only.

**Comment by domosekai** [comment] 2023-02-28 13:09
Might be duplicate of #1103

**Closed by domosekai** 2023-02-28 13:09 UTC
Labels: bug, help wanted
