### ISSUE TITLE
Hope to support MAC M1 soon

### ISSUE THREAD

**Issue by ronylee** [SoftEtherVPN/SoftEtherVPN#1505] opened 2021-11-22 12:09 UTC
Hopefully the client will support MAC M1 soon

**Comment by domosekai** [comment] 2021-11-22 15:27
What is your situation? You shouldn't open a new issue if it's a duplicate of #1331.

**Comment by metalefty** [comment] 2021-11-24 07:41
@domosekai I think the separate issue can be opened if the scope is different. #1331 looks Windows on ARM. This issue is maybe for macOS native on M1 Mac.

However, it works perfectly on GNU/Linux on Raspberry Pi. I think it should work on macOS on ARM (M1 Mac).

@ronylee I would say don't hope, ask more specifically.  Do you have any trouble running SoftEtherVPN client on M1 Mac? I'm happy to help you but what is the actual issue?

**Comment by domosekai** [comment] 2021-11-24 08:41
As the author has also commented in #1331, I assume the situation is the same (i.e. in Windows).
In macOS the situation is similar in both Apple Silicon and Intel models. SoftEther client can be built and run but the user has to install a 3rd party TAP device.

**Comment by ronylee** [comment] 2021-11-26 15:09
> 正如作者在[#1331 中](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1331)也评论过的，我认为情况是一样的（即在 Windows 中）。 在 macOS 中，情况从 Intel 模型到 Apple Silicon 都没有改变，所以我们无事可做。可以构建和运行 SoftEther 客户端，但用户必须安装第 3 方 TAP 设备。

Do you have detailed installation documents?

**Comment by domosekai** [comment] 2021-11-26 15:17
You haven't answered my question. What is your situation?

**Closed** 2021-12-07 15:32 UTC
