### ISSUE TITLE
"No Adjustments of Routing Table" option does not work

### ISSUE THREAD

**Issue by arloan** [SoftEtherVPN/SoftEtherVPN#171] opened 2015-08-27 07:31 UTC
In a VPN connection's properties dialog, open "Advanced Settings ..." dialog, check the option "No Adjuestments of Routing Table", then connect to the VPN, the system's default gateway still set to VPN server.

SoftEther client version: 4.18 build 9570,
OS: Windows 7 ultimate x64

**Comment by LikeARock47** [comment] 2016-08-26 02:14
Confirmed I also noticed this issue.  I thought this option would enable "split tunneling" by not adding a default route to the gateway on the VPN network.  However it does still add it to the routing table.  A workaround for this is to manually set the metric in the VPN adapter properties to a value higher than the metric of current default route in the table.  However it would be nice if this option worked, and then split tunneling could be enabled or disabled on a per connection basis, rather than on the virtual adapter affecting all VPN connections.

**Comment by MtCedarNet** [comment] 2016-08-26 02:44
Please read the manual.
http://www.softether.org/4-docs/1-manual/4._SoftEther_VPN_Client_Manual/4.4_Making_Connection_to_VPN_Server#4.4.18_Routing_Table_Rewrite_Process

When VPN is established, OS rewrites default gateway.
This feature is intended to add a static route in order to avoid that the route to the VPN server is lost when the default gateway has been changed.

**Comment by moatazelmasry2** [comment] 2017-11-23 23:33
As others mentioned, the issue is resolved by changing the matric in the VPN adapter.

**Closed by moatazelmasry2** 2017-11-23 23:33 UTC
