### ISSUE TITLE
what is the require package to build in debian 9?

### ISSUE THREAD

**Issue by youxiaojie** [SoftEtherVPN/SoftEtherVPN#301] opened 2017-02-13 14:41 UTC
make and dpkg-buildpackage -b
both show this error from source.

```
src/Mayaqua/Encrypt.c: In function ‘Enc_tls1_P_hash’:
src/Mayaqua/Encrypt.c:175:11: error: storage size of ‘ctx’ isn’t known
  HMAC_CTX ctx;
           ^~~
src/Mayaqua/Encrypt.c:176:11: error: storage size of ‘ctx_tmp’ isn’t known
  HMAC_CTX ctx_tmp;
           ^~~~~~~
src/Mayaqua/Encrypt.c:184:2: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
  HMAC_Init_ex(&ctx,sec,sec_len,md, NULL);
  ^~~~~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c:185:2: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
  HMAC_Init_ex(&ctx_tmp,sec,sec_len,md, NULL);
  ^~~~~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c:192:3: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
   HMAC_Init_ex(&ctx,NULL,0,NULL,NULL); /* re-init */
   ^~~~~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c:193:3: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
   HMAC_Init_ex(&ctx_tmp,NULL,0,NULL,NULL); /* re-init */
   ^~~~~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c:169:43: warning: implicit declaration of function ‘HMAC_cleanup’ [-Wimplicit-function-declaration]
 #define HMAC_CTX_cleanup(ctx)             HMAC_cleanup(ctx)
                                           ^
src/Mayaqua/Encrypt.c:212:2: note: in expansion of macro ‘HMAC_CTX_cleanup’
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
src/Mayaqua/Encrypt.c: In function ‘MdProcess’:
src/Mayaqua/Encrypt.c:460:2: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
  HMAC_Init(md->Ctx, NULL, 0, NULL);
  ^~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c: In function ‘SetMdKey’:
src/Mayaqua/Encrypt.c:476:2: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
  HMAC_Init(md->Ctx, key, key_size, md->Md);
  ^~~~~~~~~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c:476:36: warning: passing argument 4 of ‘HMAC_Init’ from incompatible pointer type [-Wincompatible-pointer-types]
  HMAC_Init(md->Ctx, key, key_size, md->Md);
                                    ^~
In file included from /usr/include/openssl/hmac.h:13:0,
                 from /usr/include/openssl/ssl.h:56,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/hmac.h:28:1: note: expected ‘const EVP_MD * {aka const struct evp_md_st *}’ but argument is of type ‘const struct env_md_st *’
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
src/Mayaqua/Encrypt.c: In function ‘NewMd’:
src/Mayaqua/Encrypt.c:492:8: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  m->Md = EVP_get_digestbyname(name);
        ^
src/Mayaqua/Encrypt.c:499:29: error: invalid application of ‘sizeof’ to incomplete type ‘struct hmac_ctx_st’
  m->Ctx = ZeroMalloc(sizeof(struct hmac_ctx_st));
                             ^~~~~~
src/Mayaqua/Encrypt.c:500:2: warning: implicit declaration of function ‘HMAC_CTX_init’ [-Wimplicit-function-declaration]
  HMAC_CTX_init(m->Ctx);
  ^~~~~~~~~~~~~
src/Mayaqua/Encrypt.c:502:24: warning: passing argument 1 of ‘EVP_MD_size’ from incompatible pointer type [-Wincompatible-pointer-types]
  m->Size = EVP_MD_size(m->Md);
                        ^
In file included from /usr/include/openssl/x509.h:23:0,
                 from /usr/include/openssl/ssl.h:50,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/evp.h:410:5: note: expected ‘const EVP_MD * {aka const struct evp_md_st *}’ but argument is of type ‘const struct env_md_st *’
 int EVP_MD_size(const EVP_MD *md);
     ^~~~~~~~~~~
src/Mayaqua/Encrypt.c: In function ‘NewCipher’:
src/Mayaqua/Encrypt.c:554:29: error: invalid application of ‘sizeof’ to incomplete type ‘struct evp_cipher_ctx_st’
  c->Ctx = ZeroMalloc(sizeof(struct evp_cipher_ctx_st));
                             ^~~~~~
src/Mayaqua/Encrypt.c: In function ‘RsaBinToPublic’:
src/Mayaqua/Encrypt.c:822:9: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
  if (rsa->e != NULL)
         ^~
src/Mayaqua/Encrypt.c: In function ‘RsaPublicToBuf’:
src/Mayaqua/Encrypt.c:857:45: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
  if (k == NULL || k->pkey == NULL || k->pkey->pkey.rsa == NULL
                                             ^~
src/Mayaqua/Encrypt.c: In function ‘NewX509’:
src/Mayaqua/Encrypt.c:2058:25: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
   ASN1_INTEGER *s = x509->cert_info->serialNumber;
                         ^~
src/Mayaqua/Encrypt.c: In function ‘RsaCheck’:
src/Mayaqua/Encrypt.c:2793:3: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
   rsa = RSA_generate_key(bit, RSA_F4, NULL, NULL);
   ^~~
In file included from /usr/include/openssl/rsa.h:13:0,
                 from /usr/include/openssl/x509.h:31,
                 from /usr/include/openssl/ssl.h:50,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
src/Mayaqua/Encrypt.c: In function ‘RsaGen’:
src/Mayaqua/Encrypt.c:2863:3: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
   rsa = RSA_generate_key(bit, RSA_F4, NULL, NULL);
   ^~~
In file included from /usr/include/openssl/rsa.h:13:0,
                 from /usr/include/openssl/x509.h:31,
                 from /usr/include/openssl/ssl.h:50,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^
src/Mayaqua/Encrypt.c: In function ‘X509ToX’:
src/Mayaqua/Encrypt.c:3977:7: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
       char *uri = (char *)ASN1_STRING_data(ad->location->d.uniformResourceIdentifier);
       ^~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
src/Mayaqua/Encrypt.c: In function ‘BioToBuf’:
src/Mayaqua/Encrypt.c:4083:12: error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
  size = bio->num_write;
            ^~
src/Mayaqua/Encrypt.c: In function ‘FreeOpenSSLThreadState’:
src/Mayaqua/Encrypt.c:4178:2: warning: ‘ERR_remove_state’ is deprecated [-Wdeprecated-declarations]
  ERR_remove_state(0);
  ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/Mayaqua/Encrypt.c:127:
/usr/include/openssl/err.h:247:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
src/Mayaqua/Encrypt.c: In function ‘InitCryptLibrary’:
src/Mayaqua/Encrypt.c:4203:2: warning: implicit declaration of function ‘SSLeay_add_all_digests’ [-Wimplicit-function-declaration]
  SSLeay_add_all_digests();
  ^~~~~~~~~~~~~~~~~~~~~~
src/Mayaqua/Encrypt.c: In function ‘DhNew’:
src/Mayaqua/Encrypt.c:5003:8: error: dereferencing pointer to incomplete type ‘struct dh_st’
  dh->dh->p = BinToBigNum(buf->Buf, buf->Size);
        ^~
Makefile:77: recipe for target 'tmp/objs/Mayaqua/Encrypt.o' failed
make: *** [tmp/objs/Mayaqua/Encrypt.o] Error 1

make from semi compiled version from downloaded biggest zip file which contain multi-platform.
/usr/bin/ld: lib/libedit.a(search.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(sig.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(term.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(tty.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(vi.o): relocation R_X86_64_32 against symbol `cv__isWord' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(vis.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(tokenizer.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(history.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(filecomplete.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(fcns.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(help.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(emacs.o): relocation R_X86_64_32 against symbol `ce__isword' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libedit.a(unvis.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_mouse.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_printw.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_scanw.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(tty_update.o): relocation R_X86_64_32 against symbol `_nc_outch' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_acs.o): relocation R_X86_64_32 against symbol `acs_map' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_options.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_setup.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_termcap.o): relocation R_X86_64_32S against symbol `_nc_globals' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_ti.o): relocation R_X86_64_32S against symbol `boolnames' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_tparm.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_tputs.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(read_entry.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(setbuf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(trim_sgr0.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(unctrl.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_color.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_mvcur.o): relocation R_X86_64_32 against symbol `_nc_outch' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_tstp.o): relocation R_X86_64_32S against symbol `_nc_outch' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_vidattr.o): relocation R_X86_64_32 against symbol `_nc_outch' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(comp_error.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(db_iterator.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(home_terminfo.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(init_keytry.o): relocation R_X86_64_32S against symbol `_nc_tinfo_fkeys' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_baudrate.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_set_term.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(lib_slkrefr.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libncurses.a(resizeterm.o): relocation R_X86_64_32 against symbol `_nc_prescreen' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(compress.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(uncompr.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(deflate.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(trees.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(zutil.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(inflate.o): relocation R_X86_64_32 against symbol `zcalloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(inftrees.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(inffast.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: lib/libintelaes.a(intel_aes.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'i_read_and_agree_the_license_agreement' failed
make[1]: *** [i_read_and_agree_the_license_agreement] Error 1
make[1]: Leaving directory '/home/allan/Downloads/VPN-CD-v4.22-9634-beta-2016.11.27/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.22-9634-beta-2016.11.27-linux-x64-64bit/vpnserver'
```

what can i do?
can you make a deb  build guide?

**Comment by moatazelmasry2** [comment] 2017-02-23 22:08
Please install the following packages:

sudo apt-get install -y build-essential libreadline-dev libssl-dev

**Comment by youxiaojie** [comment] 2017-02-27 17:45
I have got it, libreadline-dev libssl1.0-dev for compile zlib1g-dev and libncurses5-dev for link.and to be linked success, we will chang network.c to remove SSLv3_method.

**Comment by youxiaojie** [comment] 2017-02-27 17:49
about -fPIC question , not dealt it with.

**Comment by moatazelmasry2** [comment] 2017-03-02 18:52
Silly question. Is your debian 64bit OS?

**Comment by youxiaojie** [comment] 2017-03-15 01:02
yes ，debian sid 64bit

**Comment by moatazelmasry2** [comment] 2017-03-17 21:48
Sorry, I really can't figure this one out. 
The compilation should work fine though on debian8 and ubuntu 16.04

The only thing I can think of, is to run:
"sudo ldconfig"
and hope it sorts itself out

**Comment by youxiaojie** [comment] 2017-03-18 16:32
what did you point to?

> 

> Sorry, I really can't figure this one out.
> The compilation should work fine though on debian8 and ubuntu 16.04
> 
> The only thing I can think of, is to run:
> "sudo ldconfig"
> and hope it sorts itself out

**Comment by moatazelmasry2** [comment] 2017-03-19 11:12
from the definition of ldconfig:
" *ldconfig*creates the necessary links and cache to the most recent 
shared libraries found in the directories specified on the command line, 
in the file//etc/ld.so.conf/, and in the trusted directories 
(//lib/and//usr/lib/)"

sp hopefully if there are trivial errors in your shared libs, this 
command should fix them, so that SE would link successfully.

**Comment by youxiaojie** [comment] 2017-03-19 14:13
does ldconfig can deal with  -fPIC question or SSLv3_method?my english is poor,sorry

**Comment by tcjew** [comment] 2017-03-23 18:34
hey their. I got the same problem on Debian testing.
I am pretty sure the error comes form libssl which is since debiad testing on package version 1.1 and not 1.0 .

**Comment by jgdye** [comment] 2017-06-14 16:24
I just got mine to compile on my Rasbian testing install, and it required installing zlib1g-dev and libssl1.0-dev. It also required the workaround for the SSLv3 error mentiond at #246. I don't know enough about editing Debian packages to fix the dependencies in the debian folder, but this allows you to compile and run the software.

**Comment by BroncoTc** [comment] 2017-07-01 01:00
It seems debian got it's file compiled in a different way that softether did, so they cannot be linked together. I got the same issue (-fPIC) as for debian testing (after stretch release) and stretch on a DevCapsule's 64bit machine.

**Comment by PalinuroSec** [comment] 2017-07-17 10:39
hello, i am interested in having softether packaged for debian 9 too, any chance to get the sslv3 problem fixed?

p.s.
to use sslv3 in 2017 is dumb http://disablessl3.com/

**Comment by Karsonito** [comment] 2017-08-03 19:56
@PalinuroSec I found a recipe to compile in debian 9 http://www.vpnusers.com/viewtopic.php?f=7&t=8476

`sudo apt-get install zlib1g-dev libncurses5-dev libssl1.0-dev build-essential libreadline-dev git
sudo ldconfig
mkdir ~/source
cd ~/source
git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
cd SoftEtherVPN/src/Mayaqua
mv Network.c Network.c.orig
cat Network.c.orig | sed ‘s!SSLv3_method!SSLv23_client_method!g’ > Network.c
cd ../..
./configure
make`

**Comment by adminport** [comment] 2017-08-14 16:47
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by chipitsine** [comment] 2017-08-20 16:27
Debian 9 comes with openssl-1.1.0, which is not compatible with openssl-1.0.X

**Comment by PalinuroSec** [comment] 2017-08-31 18:57
hello, i have already debianized and packaged it for parrotsec.org which is based on debian testing

here you can find the debianized source code
https://dev.parrotsec.org/parrot/softether-vpn

and here you can download the build results
https://archive.parrotsec.org/parrot/pool/main/s/softether-vpn

**Comment by olih10200** [comment] 2017-09-11 09:19
One million of "Thank You" @PalinuroSec for your work, but I've needed to make some modifications on the source
[ssl.patch.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/1292004/ssl.patch.txt)

**Comment by dyleighba** [comment] 2017-09-18 05:11
@PalinuroSec You sir, are a god. Thank you very much you saved me many hours of head scratching.

**Comment by moatazelmasry2** [comment] 2017-11-30 22:46
Hi people. If I understood correctly the problem is through the comments:
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/301#issuecomment-320073384
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/301#issuecomment-326389993
Resolved. 

Also as looking at lines 13020 onwards, it looks like SoftEther is behaving as it should regarding old and new SSL. 

If everyone is happy, I'd like to close this issue within the next few days

**Closed** 2017-12-04 08:39 UTC
