### ISSUE TITLE
The RADIUS timeout window needs to be increased

### ISSUE THREAD

**Issue by mountainfury** [SoftEtherVPN/SoftEtherVPN#311] opened 2017-02-28 05:39 UTC
We need to allow for a method to update the RADIUS timeout window in config.

There is an issue with using MFA with SoftEther as the RADIUS timeout window in RADIUS.h:119 it is currently hard-coded to 10 x 1000, however we should be able to update this in configuration, or at the very least be larger.

I could update this myself in my own fork, however it would be better to have this in the main code repo.

**Comment by NoahO** [comment] 2017-02-28 05:42
There's also an open bug with long radius delays, that causes ppp based protocols to break. - https://github.com/SoftEtherVPN/SoftEtherVPN/pull/282

**Comment by mountainfury** [comment] 2017-02-28 06:01
Agreed, but if these can be changed in configuration, it will allow users to make it longer than 10 seconds then we can ensure people will be able to use these in enterprise environments.

Even 30 seconds should be good enough, just enough to allow the OOB verification to complete, the options that people will need are cellular phone calls, push notifications etc.

**Comment by justbalance** [comment] 2017-10-09 19:44
I could use this feature for MFA authentication.

**Comment by moatazelmasry2** [comment] 2017-11-28 23:57
Duplicate of issue #80 . Closing

**Closed by moatazelmasry2** 2017-11-28 23:57 UTC
Labels: duplicate
