### ISSUE TITLE
v4.10-9505-beta can not work on Ubuntu 14.04 

### ISSUE THREAD

**Issue by c2chance** [SoftEtherVPN/SoftEtherVPN#105] opened 2014-10-16 04:40 UTC
I downloaded the v4.10-9505-beta src and compiled it on my Ubuntu 14.04, and installation shows ok.
But start 'vpnclient start' command or ''vpncmd', It fails...

-- Alert: SoftEther VPN Kernel --
Fatal Error: The file "hamcore.se2" is missing or broken.
Please check hamcore.se2.

(First, reboot the computer. If this problem occurs again, please reinstall VPN software files.)

Then I reboot the computer, It occures again. 

I searched hamecore.se2 file on my computer, it likes..
~$ sudo find / -name 'hamcore.se2' -print
  /usr/vpnbridge/hamcore.se2
  /usr/vpncmd/hamcore.se2
  /usr/vpnclient/hamcore.se2
  /usr/vpnserver/hamcore.se2
  /home/chance/github/SoftEtherVPN/src/bin/BuiltHamcoreFiles/unix/hamcore.se2
  /home/chance/github/SoftEtherVPN/bin/vpnserver/hamcore.se2
  /home/chance/github/SoftEtherVPN/bin/vpnclient/hamcore.se2
  /home/chance/github/SoftEtherVPN/bin/vpnbridge/hamcore.se2
  /home/chance/github/SoftEtherVPN/bin/vpncmd/hamcore.se2

I checked the document of Installing Linux from softether.org, It said VPN software being installed to /usr/local/. Why is that?

Thanks

**Comment by uptown1919** [comment] 2015-01-27 09:25
I meet the same problem. just run it by root, everything wil be fine.
$ sudo vpnserver start

**Comment by jpillora** [comment] 2015-08-03 12:10
I had this problem when I moved the executables out of the build directory. Moving them back in and running `vpnserver` from here fixed the issue.

```
$ ls -al vpnserver/
-rwxrwxrwx 1 root root 1.9K Jul 26 02:27 Authors.txt*
drwx------ 2 root root 4.0K Aug  3 07:58 chain_certs/
drwxrwxrwx 2 root root 4.0K Aug  3 07:58 code/
-rwxrwxrwx 1 root root 1.3M Jul 26 02:27 hamcore.se2*
-rw------- 1 root root  867 Aug  3 07:58 lang.config
drwxrwxrwx 2 root root 4.0K Aug  3 07:58 lib/
-rwxrwxrwx 1 root root 2.1K Jul 26 02:27 Makefile*
-rwxrwxrwx 1 root root  31K Jul 26 02:27 ReadMeFirst_Important_Notices_cn.txt*
-rwxrwxrwx 1 root root  36K Jul 26 02:27 ReadMeFirst_Important_Notices_en.txt*
-rwxrwxrwx 1 root root  50K Jul 26 02:27 ReadMeFirst_Important_Notices_ja.txt*
-rwxrwxrwx 1 root root  58K Jul 26 02:27 ReadMeFirst_License.txt*
-rwx------ 1 root root 4.4M Aug  3 07:58 vpncmd*
-rwx------ 1 root root 4.4M Aug  3 07:58 vpnserver*

$ ./vpnserver -v
SoftEther VPN Server service program
Copyright (c) SoftEther VPN Project. All Rights Reserved.

vpnserver command usage:
 vpnserver start  - Start the SoftEther VPN Server service.
 vpnserver stop   - Stop the SoftEther VPN Server service if the service has been already started.
```

**Comment by c933103** [comment] 2016-07-09 10:12
Have same problem and windows and problem remain even if run as admin. a file with same name exist in directory but 0KB in size. Attempt to uninstall give same problem which make me impossible to reinstall

**Comment by CateyesLin** [comment] 2017-03-06 07:44
The problem is due to hamcore.se2 under `/bin/vpnbridge`, `/bin/vpnclient`, `/bin/vpncmd`, `/bin/vpnserver` is root access only.

```
$ ls -al /usr/vpnserver/hamcore.se2
-rw------- 1 root root 1296234 Mar  6 07:05 /usr/vpnserver/hamcore.se2
```

so just run the command `sudo vpnserver start`

**Comment by moatazelmasry2** [comment] 2017-11-22 01:22
This issue is a couple of years old and there are many good answers here, and I personally couldn't reproduce it, when installing under /opt and giving the correct permissions.

If things are working fine now, I'd like to close this issue in the next few days

**Comment by moatazelmasry2** [comment] 2017-12-01 19:15
PR #339 Solves this problem for vpncmd. vpnserver should be started as root. For vpnclient, I am not sure

**Comment by hongquan** [comment] 2017-12-03 02:48
@moatazelmasry2 Do you want to fix _vpnclient_? I will research. I personally have this convention:
- Start `vpnserver` and `vpnclient` as _root_, because they are services.
- Start `vpncmd` as normal user, because it is run on-off and there is already admin password to protect system config.

**Comment by moatazelmasry2** [comment] 2018-01-17 23:24
@hongquan yes true. So this issue has been answered correctly. Closing this issue

**Closed by moatazelmasry2** 2018-01-17 23:24 UTC
Labels: Close candidate, Pull Request available

**Comment by sdaau** [comment] 2019-02-23 19:13
I know this is closed, but as I stumbled on this issue on Ubuntu 18.04, here's what I've found. If I'm in my home directory:

```
~$ sudo vpncmd
-- Alert: SoftEther VPN Kernel --
Fatal Error: The file "hamcore.se2" is missing or broken.
Please check hamcore.se2.

(First, reboot the computer. If this problem occurs again, please reinstall VPN software files.)
```

However the file is present:

```
~$ ls -la /usr/local/vpnserver | grep se2
-rw-------  1 root root 1296250 Jan 15  2018 hamcore.se2
```

Just `cd` to that directory does not work:
```
~$ (cd /usr/local/vpnserver && sudo vpncmd)
-- Alert: SoftEther VPN Kernel --
Fatal Error: The file "hamcore.se2" is missing or broken.
Please check hamcore.se2.

(First, reboot the computer. If this problem occurs again, please reinstall VPN software files.)
```
... however, explicitly calling the `vpncmd` in that directory does:

```
~$ (cd /usr/local/vpnserver && sudo ./vpncmd)
vpncmd command - SoftEther VPN Command Line Management Utility
SoftEther VPN Command Line Management Utility (vpncmd command)
Version 4.25 Build 9656   (English)
Compiled 2018/01/15 10:17:04 by yagi at pc33
Copyright (c) SoftEther VPN Project. All Rights Reserved.

By using vpncmd program, the following can be achieved. 

1. Management of VPN Server or VPN Bridge 
2. Management of VPN Client
3. Use of VPN Tools (certificate creation and Network Traffic Speed Test Tool)

Select 1, 2 or 3: ^C
```
Note that vpncmd is a symlink, if you've used [softether.sh](https://gist.github.com/bouroo/30ea2e3ce065d47a44e580093aa21bb3) to install:

```
~$ ls -la `which vpncmd` 
lrwxrwxrwx 1 root root 27 Feb 23 19:43 /usr/local/bin/vpncmd -> /usr/local/vpnserver/vpncmd
```

My guess is, the `vpncmd` tries to get the path to itself, and then looks for `hamcore.se2` in the same directory; however, it probably does not resolve symlinks, so ends up with `/usr/local/bin/` as the path to itself instead of the correct `/usr/local/vpnserver/`, looks in there for `hamcore.se2`, doesn't find it, and fails.

**Comment by chipitsine** [comment] 2019-02-24 06:02
Why not to open new issue?
