### ISSUE TITLE
SoftEther  Support Kernels

### ISSUE THREAD

**Issue by Sherry0808** [SoftEtherVPN/SoftEtherVPN#1914] opened 2023-10-04 11:45 UTC
### Discussed in https://github.com/SoftEtherVPN/SoftEtherVPN/discussions/1910

<div type='discussions-op-text'>

<sup>Originally posted by **Sherry0808** September 27, 2023</sup>
Hi，

When will SoftEther support the 5.4 series of kernels?</div>

After installing Softether, I added the tap_28 interface of device A to vrf-14 and also added the tap_28 interface of device B to vrf-14. Then, I tried to connect using Softclient and access the 172.16.21.1 address of device B's tap_28 interface, but I found that it was not accessible. Our current kernel version is 5.4, so I would like to know if Softether supports the 5.4 kernel. I noticed on the official website that it explicitly states support for 2.x, 3.x, and 4.x kernels, so I want to confirm.

**Comment by chipitsine** [comment] 2023-10-04 12:50
duplicate of https://github.com/SoftEtherVPN/SoftEtherVPN/discussions/1910

**Closed by chipitsine** 2023-10-04 12:50 UTC
