### ISSUE TITLE
DNS resolution failure after #1329 in IPv4 single stack

### ISSUE THREAD

**Issue by metalefty** [SoftEtherVPN/SoftEtherVPN#1428] opened 2021-07-13 09:14 UTC
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** 26a27553b27403ac357b7126b29ad51a966d3028
**Operating system:** FreeBSD 13.0-RELEASE

IPv4 single stack. This issue does not reproduce in dual-stack environment.

@davidebeatrici Can you have a look?

```
$  build/vpncmd /tools /cmd:"trafficclient speed.softether.co.jp"
InitHamcore(): Loaded from "/usr/home/meta/SoftEtherVPN/build/hamcore.se2".
vpncmd command - SoftEther VPN Command Line Management Utility Developer Edition
SoftEther VPN Command Line Management Utility (vpncmd command)
Developer Edition
Version 5.02 Build 5180   (English)
Compiled 2021/07/13 08:16:49 by meta at softether.vmeta.jp
Copyright (c) all contributors on SoftEther VPN project in GitHub.
Copyright (c) Daiyuu Nobori, SoftEther Project at University of Tsukuba, and SoftEther Corporation.
All rights reserved.

VPN Tools has been launched. By inputting HELP, you can view a list of the commands that can be used.

VPN Tools>trafficclient speed.softether.com"
TrafficClient command - Run Network Traffic Speed Test Tool in Client Mode
Starting the client program...

-------------------------------------------------------
Network Traffic Speed Test Tool Client Setting Parameters

Destination Host Name               speed.softether.com
Destination TCP Port Number         9821
Number of TCP Connections to Establish 32
Data Transfer Direction             Full (Server < -- > Client)
Data Transmission Time              15.0 seconds
Data Correction for Ethernet Frames Yes
Measurement of Total Speed of Relay Device Input Output No
-------------------------------------------------------

The connection to server speed.softether.com (port 9821) will start. 32 TCP connections will be connected.
DnsResolver(): getaddrinfo() failed with error 4!
DnsResolve(): Could not resolve "speed.softether.co.jp". Searching for it in the cache...
The connection of TCP connection number 1 failed.
The TCP connection initialization with the server failed. Measurement will stop.
The client program has beens terminated.
Error occurred. (Error code: 1)
Connection to the server failed. Check network connection and make sure that address and port number of destination server are correct.

     --------- Mayaqua Kernel Status ---------
        Malloc Count ............... 55282
        ReAlloc Count .............. 18
        Free Count ................. 55282
        Total Memory Size .......... 38474331 bytes
      * Current Memory Blocks ...... 0 Blocks (Peek: 26936)
        Total Memory Blocks ........ 55282 Blocks
      * Current MemPool Blocks ..... 0 Blocks (Peek: 0)
        Total MemPool Mallocs ...... 0 Mallocs
        Total MemPool ReAllocs ..... 0 ReAllocs
        NewLock Count .............. 240
        DeleteLock Count ........... 240
      * Current Lock Objects ....... 0 Objects
      * Current Locked Objects ..... 0 Objects
        NewRef Count ............... 119
        FreeRef Count .............. 119
      * Current Ref Objects ........ 0 Objects
      * Current Ref Count .......... 0 Refs
        GetTime Count .............. 3
        GetTick Count .............. 13
        NewThread Count ............ 3
        FreeThread Count ........... 3
      * Current Threads ............ 0 Threads
        Wait For Event Count ....... 22

        @@@ NO MEMORY LEAKS @@@
```

It appears DnsResolver tries to resolve names via IPv6 address despite the server does not have IPv6 address.

```diff
diff --git a/src/Mayaqua/DNS.c b/src/Mayaqua/DNS.c
index f3a68410..59d95423 100644
--- a/src/Mayaqua/DNS.c
+++ b/src/Mayaqua/DNS.c
@@ -405,7 +405,7 @@ void DnsResolver(THREAD *t, void *param)
        struct addrinfo hints;
        Zero(&hints, sizeof(hints));

-       hints.ai_family = AF_INET6;
+       hints.ai_family = AF_UNSPEC;
        hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;

        struct addrinfo *results;
@@ -430,6 +430,7 @@ void DnsResolver(THREAD *t, void *param)
                                Copy(&resolver->IPv4, &ip, sizeof(resolver->IPv4));
                                ipv4_ok = true;
                        }
+                       Debug("DnsResolver(): ipv6_ok=%d, ipv4_ok=%d\n", ipv6_ok, ipv4_ok);
                }

                resolver->OK = true;
```

After I change the code like above, DNS resolution looks going well but something's still wrong. It appears strange. `speed.softether.co.jp` has only A record. Why `ipv6_ok=1`? The refactor of DnsResolver might have some regressions.

```
The connection to server speed.softether.co.jp (port 9821) will start. 32 TCP connections will be connected.
DnsResolver(): ipv6_ok=1, ipv4_ok=0
DnsResolver(): ipv6_ok=1, ipv4_ok=0
DnsResolver(): ipv6_ok=1, ipv4_ok=0
The connection of TCP connection number 1 failed.
The TCP connection initialization with the server failed. Measurement will stop.
The client program has beens terminated.
Error occurred. (Error code: 1)
Connection to the server failed. Check network connection and make sure that address and port number of destination server are correct.
```

**Comment by domosekai** [comment] 2021-07-13 13:39
If family is set to `AF_UNSPEC`, the IPv4 result will not be in RFC 4291 format and will lead to undefined result.
In fact, since our `IsIP6()` is just `IsIP4() == false`, the corrupted address sent to `IsIP4()` will of course return false, which causes `IsIP6()` to be true. It is actually neither IPv4 nor IPv6.

**Comment by domosekai** [comment] 2021-07-13 13:48
Have you ruled out the possibility that the DNS server is corrupted?
Even in a IPv4-only environment, it should work for IPv6 address resolution. I suspect that your DNS server returns SERVFAIL for AAAA lookups. 
Could you try using public servers like 8.8.8.8?
Also, if you can attach tcpdump it will be even better.

**Comment by metalefty** [comment] 2021-07-13 14:16
> Even in a IPv4-only environment, it should work for IPv6 address resolution.  The DnsResolver was working before refactoring.  I suppose the refactored resolver is corrupted. 

Yes, I know but that is not the case. I'm not resolving any IPv6 address. I resolving A record of `speed.softether.co.jp`.

**Comment by domosekai** [comment] 2021-07-13 14:42
How do you know you are resolving A record without tcpdump?

**Comment by metalefty** [comment] 2021-07-13 14:44
> If family is set to AF_UNSPEC, the IPv4 result will not be in RFC 4291 format and will lead to undefined result.
In fact, since our IsIP6() is just IsIP4() == false, the corrupted address sent to IsIP4() will of course return false, which causes IsIP6() to be true. It is actually neither IPv4 nor IPv6.

Thanks for the info. 

This is the minimum snippet to reproduce `getaddrinfo()` error. `hints` is configured as same as the SoftEther code.

https://gist.github.com/metalefty/4bf5804b0fe07aaec062e56f0bf53097
```C
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <arpa/inet.h>

int main()
{
 char *hostname = "www.softether.com";
 struct addrinfo hints, *res;
 struct in_addr addr;
 int err;
 char str[INET_ADDRSTRLEN];

 memset(&hints, 0, sizeof(hints));
 hints.ai_family = AF_INET6;
 hints.ai_flags = AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED;

 if ((err = getaddrinfo(hostname, NULL, &hints, &res)) != 0) {
   printf("error %s (%d)\n", gai_strerror(err), err);
   return 1;
 }

 addr.s_addr = ((struct sockaddr_in *)(res->ai_addr))->sin_addr.s_addr;
 inet_ntop(AF_INET, &addr.s_addr, str, INET_ADDRSTRLEN);

 printf("ip address : %s\n", str);

 freeaddrinfo(res);

 return 0;
}
```

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/b531d8e234f941f355738628f5863fc08a22c68d/src/Mayaqua/DNS.c#L408-L413

```
% ./a.out
error Non-recoverable failure in name resolution (4)
```

If I set `hints.ai_family = AF_INET;` or `AF_UNSPEC`, `getaddrinfo()` does not return any error.

```
$ ./a.out
ip address : 130.158.75.59
```

So I suspect `hints` is configured something wrong.

**Comment by domosekai** [comment] 2021-07-13 14:50
To understand why we need the refactor. I suggest you read https://www.freebsd.org/cgi/man.cgi?query=getaddrinfo&sektion=3&format=html . 
Especially these flags:
AI_ALL | AI_ADDRCONFIG | AI_V4MAPPED

**Comment by metalefty** [comment] 2021-07-13 14:51
Thanks but can you try the snippet to reproduce?

**Comment by domosekai** [comment] 2021-07-13 14:56
I don't need to try since it explains nothing.
If you set family to AF_INET, the result is in the old format not accepted by the current softether implementation. Of course you can print it and show the resolution is OK. But that was just what we were doing in the past. We have made that big change and we will not go back. 
The problem now is, why your server does not work in the new way. One reason could be freebsd has something different than Linux. Or, as I suspect, something is wrong with your DNS servers.

**Comment by metalefty** [comment] 2021-07-13 15:01
Okay, you don't need to test `AF_INET` and `AF_UNSPEC` but can you test `AF_INET6` during I take tcpdump?
If it works, it helps to know my server is working wrong.

**Comment by domosekai** [comment] 2021-07-13 15:22
I tested on Linux IPv4 only environment. Traffic client works fine. I have no freebsd experience so I can't help with that. Sorry.

**Comment by metalefty** [comment] 2021-07-13 15:34
I created a fresh Azure VM. I ran the snippet on the VM, got the same result.  I'm happy to give you access on the VM if you and @davidebeatrici want. Even if you have no FreeBSD experience, you must be able to just `cd` into the directory and run `a.out`.


The error is probably due to differences between Linux and FreeBSD, as it is unlikely that the DNS in the Azure cloud is corrupted.

**Comment by domosekai** [comment] 2021-07-13 16:29
Alright. I created my very first freebsd instance and I know where the problem is.
It's because Linux enables IPv6 by default but freebsd does not.

Note that the server does not need IPv6 access. But the kernel must enable IPv6, otherwise AF_INET6 results will not be returned.
In a IPv4-only freebsd instance, I add `ipv6_enable="YES"` to `/etc/rc.conf` and now it works.

In a Linux instance, it's controlled by a kernel option `net.ipv6.conf.all.disable_ipv6` which defaults to 0. If set to 1, you can reproduce the same issue as in freebsd.

@davidebeatrici What would you do then?

**Comment by davidebeatrici** [comment] 2021-07-13 17:21
Let's use `AF_INET` when `IsIPv6Supported()` returns `false`:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/26a27553b27403ac357b7126b29ad51a966d3028/src/Mayaqua/Network.c#L9889-L9907

**Comment by metalefty** [comment] 2021-07-13 17:22
Thanks for the test. 

BTW, this is off-topic but to be clear, IPv6 is enabled on FreeBSD by default. It is just no interfaces other than loopback interfaces have IPv6 addresses.  I think the equivalent `net.inet.conf.all.disable_ipv6` on Linux is `kern.features.inet6` on FreeBSD. It defaults to  1.

After I assign an IPv6 address on a network interface (without `ipv6_enable="YES"` in rc.conf), it starts working. It raises an error again if I remove  IPv6 address from the interface.

```
# ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
# ifconfig hn0
hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8051b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,TSO4,LRO,LINKSTATE>
        ether 00:22:48:68:ca:0e
        inet 10.9.8.8 netmask 0xffffff00 broadcast 10.9.8.255
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
# ./a.out
error Non-recoverable failure in name resolution (4)
```
```
# ifconfig hn0 inet6 fe80::cafe%hn0
# ifconfig hn0
hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8051b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,TSO4,LRO,LINKSTATE>
        ether 00:22:48:68:ca:0e
        inet 10.9.8.8 netmask 0xffffff00 broadcast 10.9.8.255
        inet6 fe80::cafe%hn0 prefixlen 64 scopeid 0x2
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
# ./a.out
(raises no error)
```


```
# ifconfig hn0 inet6  fe80::cafe%hn0 -alias
# ifconfig hn0
hn0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8051b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,TSO4,LRO,LINKSTATE>
        ether 00:22:48:68:ca:0e
        inet 10.9.8.8 netmask 0xffffff00 broadcast 10.9.8.255
        media: Ethernet autoselect (10Gbase-T <full-duplex>)
        status: active
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
# ./a.out
error Non-recoverable failure in name resolution (4)
```

**Comment by metalefty** [comment] 2021-07-13 17:28
@davidebeatrici Unfortunately, `IsIPv6Supported()` returns true in this case because it is actually supported. Just no interfaces has IPv6 addresses.

```diff
diff --git a/src/Mayaqua/DNS.c b/src/Mayaqua/DNS.c
index f3a68410..4e517c0b 100644
--- a/src/Mayaqua/DNS.c
+++ b/src/Mayaqua/DNS.c
@@ -392,6 +392,7 @@ CACHE:

 void DnsResolver(THREAD *t, void *param)
 {
+       Debug("DnsResolver(): IsIPv6Supported=%d\n", IsIPv6Supported());
        if (t == NULL || param == NULL)
        {
                return;
```

```
The connection to server speed.softether.com (port 9821) will start. 32 TCP connections will be connected.
DnsResolver(): IsIPv6Supported=1
DnsResolver(): getaddrinfo() failed with error 4!
DnsResolve(): Could not resolve "speed.softether.com". Searching for it in the cache...
The connection of TCP connection number 1 failed.
```

**Comment by domosekai** [comment] 2021-07-13 17:34
> I think the equivalent net.inet.conf.all.disable_ipv6 on Linux is kern.features.inet6 on FreeBSD. It defaults to 1.

Please note `net.inet.conf.*.disable_ipv6` is a per-interface setting. Therefore I said its counterpart is `ipv6_enable`, or in modern versions, `ifconfig_*_ipv6`.

**Comment by metalefty** [comment] 2021-07-13 17:48
I see. Anyway, `IsIPv6Suppoered()` is not appropriate method to determine which AF_INET or AF_INET6 to use in this situation. 

`ifconfig_*_ipv6` is used to assign IPv6 address on the interface, not enable/disable. Also the obsolete `ipv6_enable` is not enabling/disabling IPv6 in the current version. The name is misleading though.

**Comment by domosekai** [comment] 2021-07-13 17:55
> `ifconfig_*_ipv6` is used to assign IPv6 address on the interface, not enable/disable. Also the obsolete `ipv6_enable` is not enabling/disabling IPv6 in the current version. The name is misleading though.

Per https://www.freebsd.org/cgi/man.cgi?rc.conf(5)
> ipv6_enable
> If the variable is "YES", "inet6 accept_rtadv" is added to all of ifconfig_<interface>_ipv6 and the ipv6_activate_all_interfaces is defined as "YES".

**Comment by metalefty** [comment] 2021-07-13 18:05
Okay but it is not important now. 

The point that separate the current DNS resolution code works or not is whether any interface have IPv6 address. This cannot be checked by IsIPv6Supported(). We need to find out to do that.

**Comment by domosekai** [comment] 2021-07-13 18:05
@davidebeatrici  FYI, the glibc way of checking whether IPv6 is available is by looping through ifaddrs.
https://elixir.bootlin.com/glibc/latest/source/inet/check_pf.c#L47

**Comment by domosekai** [comment] 2021-07-13 18:09
And the softether way is probably `GetHostIPAddressList()`

**Comment by davidebeatrici** [comment] 2021-07-13 20:30
Correct.

**Closed** 2021-12-04 12:03 UTC
