### ISSUE TITLE
SoftEtherVPN Stable Edition: Disabling the JSON API publicly exposes private IP information

### ISSUE THREAD

**Issue by officialh1** [SoftEtherVPN/SoftEtherVPN#1784] opened 2023-03-01 03:27 UTC
Hi, there!

Thank you for using SoftEther.

If you are running SoftEther VPN 4.x (i.e. Stable Edition), please read the comparison with Developer Edition at: 

https://github.com/SoftEtherVPN/SoftEtherVPN#comparison-with-stable-edition

Before you submit an issue, please read the following:

Is this a question?

- If the answer is "yes", then please ask your question on [www.vpnusers.com](http://www.vpnusers.com).
The issue section on GitHub is reserved for bugs and feature requests.

- If the answer is "no", please read the following:

We provide a template which is specifically made for bug reports, in order to be sure that the report includes enough details to be helpful.

Please use or adapt it as needed.

---

### Prerequisites

* [ ] Can you reproduce? Yes
* [ ] Are you running the latest version of SoftEtherVPN_stable? Yes

**SoftEther version: v4.41-9782-beta**
**Component: Server/Controller** [Server, Client, Bridge, etc.]
**Operating system: Windows** [Windows, Linux, BSD, macOS, etc.]
**Architecture: 64bit** [64 bit, 32 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Specify brand and model. Example: AMD Ryzen 7 1800x]
VMware VM v6.5

### Description

[Description of the bug]

**Expected behavior:**
Generic error message

**Actual behavior:**
Generic error information with private IP information exposed

### Steps to reproduce

1. bool DisableJsonRpcWebApi true
2. Go the web page for the vpn controller
3. "HTTP Server at 192.168.x.x Port 443"

**Comment by domosekai** [comment] 2023-03-01 04:58
Duplicate of #959

**Closed by domosekai** 2023-03-01 04:58 UTC
