### ISSUE TITLE
carriage return character in vpn_server.config on freeBSD

### ISSUE THREAD

**Issue by cukal** [SoftEtherVPN/SoftEtherVPN#470] opened 2018-04-02 16:33 UTC
The vpn_server.config file (v4.25-9656-rtm-2018.01.15-freebsd-x64-64bit) has a carriage return character added at the end of each line when editing in vi. Cleaning the file works until the vpnserver is restarted when it flushes it current running config. When starting with a vpn_server.config file without the carriage return after a restart the ^M (0xD) character is back added in the file. 

Does not break anything but makes it hard to edit/read, temporarily remove them in vi: ```:%s/^M//g```

**Comment by moatazelmasry2** [comment] 2018-04-07 19:57
I'd be happy if you submit a pull request that solves this issue

**Comment by davidebeatrici** [comment] 2018-12-15 20:51
`CfgOutputFolderText()`:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/aa3a797edb474418d476263507f890d390f3d572/src/Mayaqua/Cfg.c#L1232

`CfgAddLine()`:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/aa3a797edb474418d476263507f890d390f3d572/src/Mayaqua/Cfg.c#L1440

The ideal solution would be to keep using `\r\n` on Windows and switch to `\n` on Unix (converting line endings if the configuration file already exists).

**Comment by chipitsine** [comment] 2019-12-28 15:38
@metalefty , can you have a look please ?

**Comment by metalefty** [comment] 2019-12-31 10:56
As far as I looked, line ending of  `vpn_server.config` is actually CRLF. It doesn't seem FreeBSD specific issue.

```
# nkf --guess=2 vpn_server.config
UTF-8 (BOM) (CRLF)
```

Also `lang.config` is saved as CRLF.

```
# nkf --guess=2 lang.config
UTF-8 (BOM) (CRLF)
```

I don't think CRLF is a issue if it behaves by design.  I'm using vim that supports CRLF instead of vi, so it isn't a issue for me. It sounds reasonable using CRLF both on Windows/Unix to keep config file portable between both OS.

![image](https://user-images.githubusercontent.com/941609/71619328-44ddc800-2c07-11ea-8c3b-4bd8796436c3.png)


However, if you board members decide to use CRLF on Windows and LF on Unix, I'm happy to help you.

**Comment by chipitsine** [comment] 2019-12-31 11:09
I'm not sure what is the issue. Is it related to proper editor choice? I.e. right editor takes those configs? If so, I would just close the issue

**Comment by metalefty** [comment] 2019-12-31 11:33
As far as I understand, the reporter complains that after manually converting config files from CRLF to LF, SoftEther converts config back to CRLF after restart/reload. I think this behaviour is by design. If you change this design, I happy to help you but it isn't a issue for me.

> Cleaning the file works until the vpnserver is restarted when it flushes it current running config. 

Also the reporter seems to use the word "clean" for LFs but I don't think LF is *cleaner* than CRLF and vice versa. They're just the difference. 

Just FYI, when opening CRLF files in `vi` (actually FreeBSD's `vi`  is `nvi`, most GNU/Linux's `vi` is `vim`), `^M` is shown at the EoL. `^M` looks like a noise. This is because `nvi` doesn't support CRLF AFAIK.
![image](https://user-images.githubusercontent.com/941609/71620136-85d7db80-2c0b-11ea-8ce5-b433c750c75c.png)

**Comment by chipitsine** [comment] 2019-12-31 12:09
yes, I understand that. some people are happy with CRLF, other like LF. I'm not sure how to satisfy both of them. Also, it introduces complexity. I'm not sure we need that complexity.

**Comment by domosekai** [comment] 2021-09-19 16:01
No changes needed.

**Closed by domosekai** 2021-09-19 16:01 UTC
Labels: help wanted
