### ISSUE TITLE
Add the option to force using ICMP and DNS over normal TCPIP connection

### ISSUE THREAD

**Issue by danyhm** [SoftEtherVPN/SoftEtherVPN#1742] opened 2023-01-10 14:59 UTC
Hello,

for some scenarios, it's preferable to use ICMP or DNS instead of the regular TCPIP connection. please add an option to force using ICMP or DNS over a normal TCPIP connection.

**Comment by domosekai** [comment] 2023-01-10 15:50
Duplicate of #1481

**Closed by domosekai** 2023-01-10 15:50 UTC
