### ISSUE TITLE
sorting error

### ISSUE THREAD

**Issue by vlaw** [SoftEtherVPN/SoftEtherVPN#140] opened 2015-03-13 09:47 UTC
![1](https://cloud.githubusercontent.com/assets/56830/6636105/e0807478-c9a7-11e4-9e02-9b4918d78f3b.png)
There are ordering problems in the two columns with red rectangule.
The unit (second,hour,day) of the value is forgotten in the first column , 
and the number value is mistreated as literal value in the second column.

**Comment by slacka** [comment] 2015-03-16 01:17
Please close this issue as a dupe of issue #99

**Closed** 2015-03-16 02:49 UTC
