### ISSUE TITLE
dhclient not working on developer edition?

### ISSUE THREAD

**Issue by ashah976** [SoftEtherVPN/SoftEtherVPN#1323] opened 2021-04-07 16:36 UTC
Downloaded the vpnserver/client versions from this repo using a fresh build of raspian OS (2021) 
I'm failing to get an IP address when connecting to a virtual hub using the virtual dhcp on the hub
After downloading the arm client from https://www.softether.org/5-download it worked right away?  

Is this a bug possibly?

Simple connection to a virtual hub with virtual dhcp enabled, but no ip received on client
using arm linux client (raspberry pi 4)
client status is connected

AccountList command - Get List of VPN Connection Settings
Item |Value
----------------------------+---------------------------------------------
VPN Connection Setting Name |
vpnclient Status |Connected
VPN Server Hostname (Direct TCP/IP Connection)
Virtual Hub |Prayertimetable
Virtual Network Adapter Name|vpnse
The command completed successfully.

So I tried again with the installation of the client from https://www.softether.org/5-download and it works fine I received the address straight away...... bug possibly?

**Comment by davidebeatrici** [comment] 2021-04-07 18:56
I can't reproduce the issue with both client and server built from the latest commit on `master`.

Please note that you have to run the DHCP client (e.g. `dhclient`) manually for the interface, for example:
```
sudo dhclient vpn_vpnse
```

**Comment by davidebeatrici** [comment] 2021-07-04 08:00
Closing in favor of #1298.

**Closed by davidebeatrici** 2021-07-04 08:00 UTC
