### ISSUE TITLE
Feature Req: Vpn Kill Switch

### ISSUE THREAD

**Issue by lecatos** [SoftEtherVPN/SoftEtherVPN#1643] opened 2022-08-06 19:03 UTC
This vpn is dogsheet since it doesn't even have basic privacy feature like Vpn Kill Switch. i was using this vpn and then all of the sudden my vpn connection disconnected and now my ip is exposed and my life is fked which defeats the purpose of using vpn to stay anonymous. Cmon dev you can do better.

**Comment by domosekai** [comment] 2022-09-24 08:39
Duplicate of #1634

**Closed by domosekai** 2022-09-24 08:39 UTC
