### ISSUE TITLE
Support of accounting via Radius?

### ISSUE THREAD

**Issue by mproper** [SoftEtherVPN/SoftEtherVPN#117] opened 2014-11-24 18:07 UTC
HI, is any plans for adding radius accounting support?

**Comment by moatazelmasry2** [comment] 2017-11-22 23:52
I marked another similar ticket as a feature request and I'm trying to find the most requested features of this project to announce. This ticket is a duplicate of #101 . Please thumbs up there if you want this implemented.

**Closed** 2017-11-22 23:55 UTC
Labels: duplicate, feature
