### ISSUE TITLE
Conflict with win11 taskbar. The taskbar icon needs to be clicked multiple times before other programs can be opened

### ISSUE THREAD

**Issue by easycold** [SoftEtherVPN/SoftEtherVPN#1591] opened 2022-05-11 02:31 UTC
hi,there.
I found a bug.
Conflict with win11 taskbar. The taskbar icon needs to be clicked multiple times before other programs can be opened
Please fix it.

**Comment by metalefty** [comment] 2022-05-11 02:32
Can you share screenshots?

**Comment by domosekai** [comment] 2022-05-11 02:41
I can't reproduce this bug with the latest build. What is the version you are using?

**Comment by domosekai** [comment] 2022-05-11 02:42
Please download the latest build from azure artifact or build from source according to our instructions.

**Comment by easycold** [comment] 2022-05-11 06:51
The version I use is     softether-vpnclient-v4.39-9772-beta-2022.04.26-windows-x86_x64-intel.exe (53.37 MB)]
my CPU is AMD R7 5800H,  Is AMD processor causing this problem?

**Comment by domosekai** [comment] 2022-05-11 07:28
v4.39 is not supported at this repo, please use the latest build 5.02

**Comment by metalefty** [comment] 2022-05-11 08:43
SoftEtherVPN 4.x and 5.x are maintained and developed by separate teams.  If you want to stay on 4.39, the following forum would be a place to ask that.

https://www.softether.org/7-forum

**Comment by domosekai** [comment] 2022-05-13 07:36
I probably have figured out what the author was saying.
When client manager is in focus, right click on other icons in the taskbar does not work. Left click works but will result in the new window being opened in background.

**Comment by easycold** [comment] 2022-05-25 01:16
hi,there.  Now my left button often doesn't work on the taskbar.
Since the problem is found, why not merge the code? Please fix the bug. Thank you very much.

**Comment by easycold** [comment] 2022-05-25 01:18
hi,there.  Now my left button often doesn't work on the taskbar.
Since the problem is found, why not merge the code? Please fix the bug. Thank you very much.

**Comment by domosekai** [comment] 2022-05-25 01:40
You have not confirmed if the fix works for you. And apparently my description of the phenomenon differs from yours.

**Comment by easycold** [comment] 2022-05-25 08:50
You need to package and release before I can test whether it works. I downloaded the latest 5.02, which is also a phenomenon. Please refer to the screenshot.
![700505f5e0fe9925f870db4669a85edf8db17150](https://user-images.githubusercontent.com/14304166/170222064-3bc08023-bb5c-4503-aee2-188432fb1e95.gif)

**Comment by domosekai** [comment] 2022-05-25 10:21
Please build from source to verify.
Your video does not show how softether was involved. I didn't even see you have launched the CM. 
I suspect if we were talking about the same thing.

**Comment by domosekai** [comment] 2022-05-26 03:54
Merged. Thank you.

**Closed by domosekai** 2022-05-26 03:54 UTC
