### ISSUE TITLE
Android 12 no  supports L2TP. When will softether be updated to support IKEV2?

### ISSUE THREAD

**Issue by Jabiler** [SoftEtherVPN/SoftEtherVPN#1720] opened 2022-12-05 11:35 UTC
Android 12 no  supports L2TP. When will softether be updated to support IKEV2?

**Comment by IngwiePhoenix** [comment] 2022-12-05 12:15
LineageOS 19.1 based on Android 12:

![Screenshot_20221205-131454_Einstellungen](https://user-images.githubusercontent.com/2893716/205635059-121f37c5-4a72-4f71-b48e-c5cf6542fae2.png)

I can see L2TP just fine. Maybe your vendor's Android ROM has it disabled?

**Comment by domosekai** [comment] 2022-12-13 12:27
Duplicate of #13

**Closed by domosekai** 2022-12-13 12:27 UTC
