### ISSUE TITLE
cross-compile on arm/mips (linux) breaks because of <cpuid.h>

### ISSUE THREAD

**Issue by Andy2244** [SoftEtherVPN/SoftEtherVPN#574] opened 2018-07-22 14:08 UTC
- [x] Can you reproduce?
- [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** git- 879dc8f
**Component:** Server
**Operating system:** Linux
**Architecture:** 32 bit/arm/mips

### Description
The commit that added `cpuid.h` to `Encrypt.c` breaks cross-compiling, because only i386 targets have support for <cpuid.h> via gcc and the file is not included/copied by most cross-compile sdk's on other targets.

Maybe `/proc/cpuinfo` and checking for the `aes` flag could be used on unsupported linux/bsd platforms instead? 
Some arm/mips have aes support, but i'm not sure what has to-be in-place to actually get this working on none i386 platforms.

**Expected behavior:**
Be able to cross-compile via cmake for arm/mips platforms.

**Actual behavior:**
```
/src/Mayaqua/Encrypt.c:151:10: fatal error: cpuid.h: No such file or directory
 #include <cpuid.h> // For __get_cpuid()
```
### Steps to reproduce
Try to cross-compile for arm/mips via openwrt and current master.

**Comment by davidebeatrici** [comment] 2018-07-22 21:14
Duplicate of #573.

**Closed by davidebeatrici** 2018-07-22 21:14 UTC
