### ISSUE TITLE
Windows installer build/runtime error/crash

### ISSUE THREAD

**Issue by BlackHoleFox** [SoftEtherVPN/SoftEtherVPN#689] opened 2018-09-07 02:08 UTC
Evening. I was trying to build the Windows installers on my machine, which I have done successfully in the past but it seems something in the past few weeks has changed and it now fails. Wondering if anyone could point me in a good direction for a fix. All the code compiles fine until the installers start to build:

```powershell
λ  .\src\BuildAll.cmd
..(Code building)...
Executing 'X:\Softether\SoftEtherVPN\src\bin\BuildUtil.exe /CMD:ReleaseWin32 all /IGNOREERROR:no /SERIAL:no'...
BuildUtil command - VPN Build Utility

Copyright (c) SoftEther VPN Project. All Rights Reserved.

ReleaseWin32 command - Builds Win32 installer package files.
1 / 2: Executing for 'softether_open-vpnserver_vpnbridge-windows-x86_x64-intel'...
2 / 2: Executing for 'softether_open-vpnclient-windows-x86_x64-intel'...
Waiting child processes...
1 / 2 (softether_open-vpnserver_vpnbridge-windows-x86_x64-intel):
       * Error *
2 / 2 (softether_open-vpnclient-windows-x86_x64-intel):
       * Error *

System.ApplicationException: 2 Errors.
   at BuildUtil.BuildUtilCommands.ReleaseWin32(ConsoleService c, String cmdName, String str)

BuildUtil: fatal error C0001: 2 Errors.
System.ApplicationException: Child process 'X:\Softether\SoftEtherVPN\src\bin\BuildUtil.exe' returned error code 1.
   at BuildUtil.Win32BuildUtil.ExecCommand(String exe, String arg, Boolean shell_execute)
   at BuildUtil.Win32BuildUtil.ExecCommand(String exe, String arg)
   at BuildUtil.BuildUtilCommands.All(ConsoleService c, String cmdName, String str)

BuildUtil: fatal error C0001: Child process 'X:\Softether\SoftEtherVPN\src\bin\BuildUtil.exe' returned error code 1.

X:\Softether\SoftEtherVPN\src\bin>if errorlevel 1 exit /b 1
```

Thanks!

**Comment by davidebeatrici** [comment] 2018-09-07 12:49
Hi,

Is your repository up-to-date?

The latest change to the build system has been applied in #676.

**Comment by chipitsine** [comment] 2018-09-07 13:41
@davidebeatrici , do we print version during build ?

**Comment by davidebeatrici** [comment] 2018-09-07 13:46
No, but the build is failing when creating the version string.

**Comment by BlackHoleFox** [comment] 2018-09-07 15:33
It was a fresh `git clone` from about 30 minutes before I sent this issue.

**Comment by chipitsine** [comment] 2018-09-07 16:10
so... we do not catch "stderr" message, right ?

**Comment by davidebeatrici** [comment] 2018-09-07 16:18
We can get details about the exception, if the debug symbols are available.

**Comment by BlackHoleFox** [comment] 2018-09-07 17:04
When I get off work, I can run it again and give you guys anything else you need from the output if needed.

**Comment by BlackHoleFox** [comment] 2018-09-08 13:55
This is the output from the other console that the `buildAll.cmd` spawns in case it helps.
```powershell
BuildUtil command - VPN Build Utility

Copyright (c) SoftEther VPN Project. All Rights Reserved.

ReleaseWin32 command - Builds Win32 installer package files.
Building 'softether_open-vpnserver_vpnbridge-windows-x86_x64-intel' - SoftEther VPN Server and VPN Bridge (Ver 5.01, Build 9657, Intel) for Windows...
Waiting for Semaphore...
Done.
Executing 'X:\Softether\SoftEtherVPN\src\bin\vpnsetup.exe /SFXMODE:vpnserver_vpnbridge /SFXOUT:"X:\Softether\SoftEtherVPN\src\tmp\Release\softether_open-vpnserver_vpnbridge-v5.01-9657-unstable-2018.09.08-windows-x86_x64-intel.exe"'...
Skipping the code signing for 'X:\Softether\SoftEtherVPN\src\tmp\Release\softether_open-vpnserver_vpnbridge-v5.01-9657-unstable-2018.09.08-windows-x86_x64-intel.exe' in the build process. You can insert your own authenticode sign process here.


ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...
```

**Comment by BlackHoleFox** [comment] 2018-09-11 21:49
@davidebeatrici Question not strictly related to this but couldn't find a solid answer: Did the latest binary release of SoftEther (9669 Beta) implement the TLS changes or only the IPSec changes?

**Comment by davidebeatrici** [comment] 2018-09-11 21:50
Only the IPsec changes: https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/commit/abe19458ffdfd75664176d4e41e448ad3b7a4f22

**Comment by BlackHoleFox** [comment] 2018-09-11 21:52
Ah I see, thanks!

**Comment by davidebeatrici** [comment] 2018-09-11 21:52
You're welcome!

**Comment by BlackHoleFox** [comment] 2018-09-18 01:04
@davidebeatrici Has there been any progress on this issue by chance? I cloned a fresh copy and still encountered the same build error.

**Comment by davidebeatrici** [comment] 2018-09-18 01:12
Try to check where the following function is failing:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/8f53bf23e71182be4a9b30da8a8eb79ee022cb95/src/BuildUtil/BuildUtilCommands.cs#L764-L907

**Comment by BlackHoleFox** [comment] 2018-09-18 05:05
It seems to be failing here at the child processes when they attempt to build:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/8f53bf23e71182be4a9b30da8a8eb79ee022cb95/src/BuildUtil/BuildUtilCommands.cs#L877-L893

```powershell
Waiting child processes...
1 / 2 (softether_open-vpnserver_vpnbridge-windows-x86_x64-intel):
       * Error *
2 / 2 (softether_open-vpnclient-windows-x86_x64-intel):
       * Error *```

**Comment by BlackHoleFox** [comment] 2018-09-18 22:01
It seems to be failing here at the child processes when they attempt to build:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/8f53bf23e71182be4a9b30da8a8eb79ee022cb95/src/BuildUtil/BuildUtilCommands.cs#L877-L893

```powershell
Waiting child processes...
1 / 2 (softether_open-vpnserver_vpnbridge-windows-x86_x64-intel):
       * Error *
2 / 2 (softether_open-vpnclient-windows-x86_x64-intel):
       * Error *```

**Comment by davidebeatrici** [comment] 2018-09-18 22:03
What are the values of `versionMajor`, `versionMinor` and `versionBuild`?

**Comment by BlackHoleFox** [comment] 2018-10-29 15:34
@davidebeatrici So CMake successfully generated the files and I opened them in VS Studio 2017, however im unsure how to proceed from here. If you wouldn't mind explaining it some, I want to add more info to the `BUILD_WINDOWS.md` on how to develop using the new CMake process.

**Comment by davidebeatrici** [comment] 2018-10-29 15:49
@BlackHoleFox Sure, no problem!

You can either:

- Import the CMake project in Visual Studio 2017, which is what I personally recommend
- Generate Visual Studio 2017 project files (default CMake generator)
- Generate an NMake makefile by specifying `-G "NMake Makefiles"` (as we do with AppVeyor)

Right now you probably have the Visual Studio 2017 project files, you should be able to build the solution.

**Comment by BlackHoleFox** [comment] 2018-10-29 17:17
Alright @davidebeatrici . So I opened Visual Studio 2017, clicked `Open -> Cmake` and pointed it at the repository's CMakeList file. This works just fine. I then go to the toolbar and select vpnclient.exe and try to run it in debug mode. My build console spits out the same thing 100 times before stopping and giving an error of `manifest 'build.ninja' still dirty after 100 tries`.

The repeated entry in the Output terminal is this:
```powershell
>------ Build started: Project: CMakeLists, Configuration: Debug ------
<trimmed by 99 entries>
[0/1] "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -HC:\Users\Fox\Documents\SoftEtherVPN -B"C:\Users\Fox\CMakeBuilds\2d0f08d5-ea76-6d3e-87bf-237c6568fd6e\build\x64-Debug (default)"
  -- Build date: 29/10/2018
  -- Build time: 17:11:57
  CMake Warning (dev) at src/Mayaqua/3rdparty/zlib/CMakeLists.txt:4 (project):
    Policy CMP0048 is not set: project() command manages VERSION variables.
    Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.
  
    The following variable(s) would be set to empty:
  
      PROJECT_VERSION
      PROJECT_VERSION_MAJOR
      PROJECT_VERSION_MINOR
      PROJECT_VERSION_PATCH
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/Fox/CMakeBuilds/2d0f08d5-ea76-6d3e-87bf-237c6568fd6e/build/x64-Debug (default)
```

**Comment by BlackHoleFox** [comment] 2018-10-29 17:32
After removing the `build` and `tmp` directories it still has the same behavior, including when VS is restarted.

**Comment by chipitsine** [comment] 2018-10-30 03:46
@BlackHoleFox , new guide regarding CMake on windows will be really nice

**Comment by BlackHoleFox** [comment] 2018-10-30 04:32
@chipitsine Very much so. Just need to resolve these build errors and take notes for later.

**Comment by davidebeatrici** [comment] 2018-10-30 10:45
@BlackHoleFox I can't reproduce the issue.

Try to delete the `CMakeBuilds` directory inside your user's directory, it contains the CMake cache.

**Comment by BlackHoleFox** [comment] 2018-10-30 13:10
@davidebeatrici Once I actually grabbed the MFC C++ class support, this has fixed the issue. Visual Studio now seems to build everything fine, and the debug .exe's generated work as expected.

**Comment by BlackHoleFox** [comment] 2018-10-30 13:17
Not sure if this is supposed to happen right now, but the `vpnclient.exe` will install the service, but cannot start it, even when trying a seperate `/start` command.

**Comment by BlackHoleFox** [comment] 2018-10-30 13:32
If thats the case, how do you test to see if new GUI elements and stuff like that worked as intended?

**Comment by davidebeatrici** [comment] 2018-10-30 13:36
I see that you're using Cmder, which makes it easier:

1. Execute `vpntest c` in a tab opened as administrator (in order to access the virtual network adapter).
2. Open a new tab and execute `vpntest cm` in order to run VPN Client Manager.

**Comment by davidebeatrici** [comment] 2018-10-30 14:32
It's only required to build the drivers: https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by BlackHoleFox** [comment] 2018-10-30 19:33
Well, Visual Studio 2017 has that ATL/MFC support, you just need to specify that you want it. When I get a bit of time after work i'll add some stuff to info regarding CMake on Windows. I'm also going to make a GitHub Wiki entry that has a more step by step guide for setting up all the needed toolings for Windows Development.

**Comment by davidebeatrici** [comment] 2018-10-30 19:36
Excellent, thank you very much!

**Comment by BlackHoleFox** [comment] 2018-10-31 04:15
@davidebeatrici So after trying to run the full installer builder, the error persists from previously. I got the numbers you requested though
```
versionMajor: 5
versionMinor: 1
versionBuild: 9662
```

**Comment by chipitsine** [comment] 2018-11-05 07:58
@krugdenis, can you have a look at windows event viewer?

**Comment by chipitsine** [comment] 2018-11-05 09:29
Nice. Can you try to build and investigate more, I.e. adding debug info, break points, etc?

**Comment by krugdenis** [comment] 2018-11-06 11:42
I've used BuildAll.cmd with VS2008SP1 and WDK, builded installer (softether_open-vpnclient-v5.01-9662-unstable-2018.11.06-windows-x86_x64-intel.exe) crasches after license agreement too

**Comment by chipitsine** [comment] 2018-11-06 11:50
@krugdenis , it is great
can you add some debug info to you build and find a place where it crashes ?

**Comment by chipitsine** [comment] 2018-11-06 16:17
@krugdenis 

I could not reproduce installer crash.
would be nice if you could investigate it in depth

**Comment by krugdenis** [comment] 2018-11-06 16:38
@chipitsine don't know why, I've tried installing on two different laptops, Windows x64 1809 and Windows x86 1809, both are crashing after license agreement :( I don't know how to catch a bug

**Comment by BlackHoleFox** [comment] 2018-11-06 16:40
Better step then im at, mine still crashes when trying to build the installer.

**Comment by krugdenis** [comment] 2018-11-06 16:42
@BlackHoleFox it crashes after making 2 installers, softether_open-vpnclient-v5.01-9662-unstable-2018.11.06-windows-x86_x64-intel.exe and softether_open-vpnserver_vpnbridge-v5.01-9662-unstable-2018.11.06-windows-x86_x64-intel.exe

**Comment by chipitsine** [comment] 2018-11-06 17:22
@krugdenis 

according to windows event viewer log (provided by you), it crashes when executing certain command.
can you try to run such command from command line (i.e. taking all neccessary files from fresh build)

if it still crashes, you can add debug messages to various points of vpninstall.exe

**Comment by chipitsine** [comment] 2018-11-07 06:40
@krugdenis 

 а можете включить сохранение WER-отчетов ?

https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps

пара ключей в реестре.
и потом каким-то образом передать нам сохраненный дамп

**Comment by davidebeatrici** [comment] 2018-11-15 17:49
@solipse @krugdenis Which version of Windows 10 are you running?

I can't reproduce the issue on build 1607 and 1809.

**Comment by solipse** [comment] 2018-11-15 18:18
@davidebeatrici  Win 10 x86 1809 and Win 7 SP1 x86

**Comment by davidebeatrici** [comment] 2018-11-15 20:34
I couldn't reproduce the issue on a fresh installation of Windows 7 x86 Service Pack 1.

Which version of Windows 7 and Windows 10 do you have (Home, Pro, ...)?

**Comment by krugdenis** [comment] 2018-11-16 05:17
> I couldn't reproduce the issue on a fresh installation of Windows 7 x86 Service Pack 1.
> 
> Which version of Windows 7 and Windows 10 do you have (Home, Pro, ...)?

Windows 10 1809 17763 X86\X64 (RU), I've downloaded softether-vpnclient-v5.01-9663-2018.11.07-windows-x86_x64-intel.exe and softether-vpnserver_vpnbridge-v5.01-9663-2018.11.07-windows-x86_x64-intel.exe from releases, after checking "I agree to license ..." and pressing "Next" installation just crashing, without any visible error.

**Comment by solipse** [comment] 2018-11-16 09:31
@chipitsine 
softether-vpnserver_vpnbridge-v5.01-9663-2018.11.07-windows-x86_x64-intel.exe
Windows 10 Home x86 1809 11767.107
Mini dump https://yadi.sk/d/Q9r0T81r62JbTA

**Comment by chipitsine** [comment] 2018-11-17 13:42
@solipse 


when I import your dump to WinDbg.exe (you can try it yourself)
and run `!analyze –v`

I get

![screenshot from 2018-11-17 18-37-51](https://user-images.githubusercontent.com/2217296/48661726-798ccf80-ea98-11e8-9106-c8b4429c61bf.png)


looks much like null pointer dereference, but we do not provide pdb with releases.

@davidebeatrici , what do you think, should we add pdb as well ?

**Comment by davidebeatrici** [comment] 2018-11-17 16:57
@chipitsine Definitely, we should provide all `.pdb` files in an archive.

**Comment by davidebeatrici** [comment] 2018-11-18 03:30
Pull request: #811

**Comment by chipitsine** [comment] 2018-11-18 05:44
@solipse , can you reproduce crash using this installer https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/builds/20381447/job/j7vdnupi9c5t7w79/artifacts ?

it is better, beacuse we have PDB and WinDbg will show us full stack trace

can you provide dmp ?

**Comment by chipitsine** [comment] 2018-11-18 07:17
I was able to use pdb with provided dmp

![screenshot from 2018-11-18 12-14-30](https://user-images.githubusercontent.com/2217296/48669702-d5ecff00-eb2b-11e8-833a-c0d76ca7cf25.png)


stay tuned, I'll provide PR

**Comment by solipse** [comment] 2018-11-28 13:31
@chipitsine
Windows 10 Home x86 1809 17763.134
softether-vpnserver_vpnbridge-v5.01-9665-2018.11.28-windows-x86_x64-intel.exe
Dump https://yadi.sk/d/3dc3HDuyDS3UoA

**Comment by chipitsine** [comment] 2018-11-28 16:01
Thanks, will have a look soon

**Comment by chipitsine** [comment] 2018-11-28 17:57
you've got NULL here
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Cedar/SW.c#L5178

@davidebeatrici , have a look

**Comment by chipitsine** [comment] 2018-11-28 18:34
@solipse , I created quick and dirty fix for your issue

https://github.com/chipitsine/SoftEtherVPN/commit/f985a50f310766e1a1fdce435e521b3c1bb0c1e3

here's test installer, please try:

https://ci.appveyor.com/project/chipitsine/softethervpn/builds/20624946/job/jlmcjgq9jl9xfynq/artifacts

**Comment by solipse** [comment] 2018-11-28 18:47
@davidebeatrici, installer works, server manager runs and works fine, tested it only 
Thanks

**Comment by chipitsine** [comment] 2018-11-28 20:11
ok, I'll try to add better handling of missing "warning_XXX.txt" files

**Comment by davidebeatrici** [comment] 2018-11-28 20:58
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/bf0d5c551e720e6e47a8e09cea27f16809c78699/src/Cedar/SW.c#L5177-L5184

`ReadDump()` returns `NULL` because `warning_ru.txt` is not found, `SeekBuf()` and `WriteBuf()` check whether the passed buffer is `NULL`, but at line 5184 we try to access the raw buffer in the non-existent buffer, causing a crash.

The ideal fix would be to check whether `ReadDump()` returns `NULL`. If it does we should try to read `warning_en.txt` and, if that file is missing too, we should exit with an alert window.

**Comment by chipitsine** [comment] 2018-11-28 21:02
there're other issues with those warning files.
accidently we broken CRLF there (I noticed when I added warning_ru.txt)
since nobody reported that, maybe it is time to drop those files )) ? or to ignore if they are missing ... or add check like one we already have for "stb" files

**Comment by chipitsine** [comment] 2018-11-28 21:03
SeekBuf on NULL, yeah, it was great

**Comment by chipitsine** [comment] 2018-11-29 22:02
resolved in https://github.com/SoftEtherVPN/SoftEtherVPN/pull/826

**Closed by chipitsine** 2018-11-29 22:02 UTC
Labels: build & release, os/Windows

**Comment by BlackHoleFox** [comment] 2019-02-18 21:34
@davidebeatrici Sorry to drag a dead issue up again, didn't want to open a new one for it. It's the same issue I have been having for months now where the full build of SoftEtherVPN crashes for me during the final `BuildUtil.exe` steps. Would you mind taking another look if possible?

```powershell
Executing 'X:\SoftEtherVPN\SoftEtherVPN\src\bin\BuildUtil.exe /CMD:ReleaseWin32 all /IGNOREERROR:no /SERIAL:no'...
BuildUtil command - VPN Build Utility

Copyright (c) SoftEther VPN Project. All Rights Reserved.

ReleaseWin32 command - Builds Win32 installer package files.
1 / 2: Executing for 'softether_open-vpnserver_vpnbridge-windows-x86_x64-intel'...
2 / 2: Executing for 'softether_open-vpnclient-windows-x86_x64-intel'...
Waiting child processes...
1 / 2 (softether_open-vpnserver_vpnbridge-windows-x86_x64-intel):
       * Error *
2 / 2 (softether_open-vpnclient-windows-x86_x64-intel):
       * Error *

System.ApplicationException: 2 Errors.
   at BuildUtil.BuildUtilCommands.ReleaseWin32(ConsoleService c, String cmdName, String str)

BuildUtil: fatal error C0001: 2 Errors.
System.ApplicationException: Child process 'X:\SoftEtherVPN\SoftEtherVPN\src\bin\BuildUtil.exe' returned error code 1.
   at BuildUtil.Win32BuildUtil.ExecCommand(String exe, String arg, Boolean shell_execute)
   at BuildUtil.Win32BuildUtil.ExecCommand(String exe, String arg)
   at BuildUtil.BuildUtilCommands.All(ConsoleService c, String cmdName, String str)

BuildUtil: fatal error C0001: Child process 'X:\SoftEtherVPN\SoftEtherVPN\src\bin\BuildUtil.exe' returned error code 1.

X:\SoftEtherVPN\SoftEtherVPN\src\bin>if errorlevel 1 exit /b 1```
