### ISSUE TITLE
Softether VPNSERVER 99% cpu Usage

### ISSUE THREAD

**Issue by AdroitAdorKhan** [SoftEtherVPN/SoftEtherVPN#1239] opened 2020-11-12 17:40 UTC
### Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:**
**Component:** [Server]
**Operating system:** [Linux]
**Architecture:** [64 bit]

[In case it's a computer with known specs, such as the Raspberry Pi, you can specify it omitting the details.]
**Processor:** [Intel Xeon Processor (Skylake, IBRS)]

### Description

[Description of the bug]

Whenever I use securenat on my kvm server, cpu usage goes to 99%. Even with zero user connected, just whenever I enable securenate, vpnserver usage goes to 99%+-. And, it causes issue with the internet speed. 

### Steps to reproduce

1. [Enable Secure Nat On Server]
2. [Check cpu process, and VPN server hits to 99%]
3. [Disabling Secure NAT fixes the issue. Local bridge doesnt work for me, IDK why.]

**Comment by davidebeatrici** [comment] 2020-11-13 01:39
Could you try to enable `DisableIpRawModeSecureNAT` in the server's configuration, please?

**Comment by AdroitAdorKhan** [comment] 2020-11-13 13:58
@davidebeatrici Yes. It was already enabled. But still no luck. vpnserver always stuck at top of cpu usage.
![image](https://user-images.githubusercontent.com/9679103/99079717-82aec980-25ea-11eb-8c1f-8e3261a6faff.png)

**Comment by DainBB** [comment] 2020-11-29 02:51
Had exactly the same issue and also on KVM, fixed by configuring tap instead of using bridge on interface.

**Comment by AdroitAdorKhan** [comment] 2020-11-29 02:52
@DainBB Can you send me a guide? Or, tell me what you did?

**Comment by DainBB** [comment] 2020-11-29 03:02
Connect to VPN server in Server manager - Click Local Bridge Settting
Delete existing bridge on top part of the screen

At the bottom part of the screen pick Virtual Hub name from dropdown list, then instead of "Bridge with Physical Existing Network Adapter" choose "Bridge with New Tap Device"
Give some <name> for tap, tap interface will be created as tap_<name>, click "Create Local Bridge"

That's it, you should see tap_<name> in ifconfig -a output on your server and you can enable SmartNAT after that, on my VM CPU utilization never goes above 10% with this setup, before I created tap it was 80% on idle.

**Comment by AdroitAdorKhan** [comment] 2020-11-29 03:05
@DainBB Thanks a lot mate. But I am in a rush, can you please explain the SmartNAT part? That would be a great help.

**Comment by DainBB** [comment] 2020-11-29 03:06
It's SecureNAT, sorry, you know how to enable it.

**Comment by AdroitAdorKhan** [comment] 2020-11-29 03:08
@DainBB did you make any change in the SecureNAT config with new TAP interface?

**Comment by DainBB** [comment] 2020-11-29 03:08
No changes, all default settings

**Comment by AdroitAdorKhan** [comment] 2020-11-29 03:09
@DainBB Thanks again mate! You are awesome!

**Comment by libnumafly** [comment] 2020-11-30 01:26
Hi @AdroitAdorKhan nice to meet you and sorry for sounding your inbox, DainBB's solution is works for your problem?

**Comment by libnumafly** [comment] 2020-11-30 01:39
Hi @AdroitAdorKhan nice to meet you and sorry for sounding your inbox, DainBB's solution is works good for your problem?
Years ago I encountered same problem that cpu usage pumps up to 100% and slow down the speed.

That time, found caused by LOCAL BRIDGE and SECURE-NAT bothes enabled.
then, disable LOCAL BRIDGE and simply enable SECURE-NAT is works to solve the problem...

AdroitAdorKhan's problem is like this?

**Comment by AdroitAdorKhan** [comment] 2020-11-30 03:34
Hello @libnumafly I used a different approach there. I used dnsmasq and bridge, and it's working super fine now!

**Comment by libnumafly** [comment] 2020-11-30 08:00
Got it, thanks reply @AdroitAdorKhan !

**Comment by gclouduser** [comment] 2021-08-14 09:49
Oh eta age bolle too hoto

**Closed** 2021-09-18 13:12 UTC
