### ISSUE TITLE
Request to add TLS auth to OpenVPN emulation

### ISSUE THREAD

**Issue by rwasef1830** [SoftEtherVPN/SoftEtherVPN#26] opened 2014-02-13 20:05 UTC
Hello SoftEtherVPN team,
I would like to request support for a feature from OpenVPN server to use a preshared key to authenticate at TLS level before initiating connection.

Here's an explanation of the feature:
https://openvpn.net/index.php/open-source/documentation/howto.html#security

**Comment by moatazelmasry2** [comment] 2017-11-22 01:45
This is a duplicate of issue #55 . If it is ok. I'll close this issue in favor of tracking changes in the other issue.

**Closed** 2017-11-22 01:45 UTC
Labels: feature

**Comment by GRAUPS** [comment] 2025-06-25 04:45
I know this is an old ticket, but I don't think the OP's issue was ever addressed in #55 as stated. We can now authenticate users with certificates alone, but I haven't found any examples on how to enable tls-auth or tls-crypt on the softether OpenVPN server, as described in the OP's link... [https://openvpn.net/index.php/open-source/documentation/howto.html#security](url)

Did I miss a setting somewhere?
