### ISSUE TITLE
Adding new features to SoftEther software

### ISSUE THREAD

**Issue by mahdaviyousefiamir378** [SoftEtherVPN/SoftEtherVPN#1735] opened 2022-12-28 14:30 UTC
Greetings and courtesy 

Please add the following items to the software if possible
The ability to set the charge, for example, 50 gig for each user (I went to the options and did not find an option to set the limit, for example, assign 50 gigs to the plan. The user gets 50 gigs, and when the limit is reached, it is cut off and requested again (charge) - Ability to add connection of any device with MAC address to Softher VPN Linux server and Softher Manager For Windows.

Please update SofEther management software for new Mac operating systems with Apple Silicon architecture processor (M1-M2).

Will these features be added in future updates?
Please, if possible, tell me the date of adding these facilities, I would appreciate it

### Prerequisites

* [yes] Can you reproduce?
* [yes ] Are you running the latest version of SoftEtherVPN?

**SoftEther version:*v4.41-9782-beta *
**Component:** [Server, Client, Bridge, etc.]
**Operating system:** [Windows, Linux(Server),macOS, ]
**Architecture:*Intel Laptop ,Laptop Apple Silicon(M1 ,M2)* [64 bit, 32 bit]
Thanks & Regards
Amir Mahdavi Yousefi

**Comment by domosekai** [comment] 2023-01-08 14:10
Duplicate of #1389

**Closed by domosekai** 2023-01-08 14:10 UTC
