### ISSUE TITLE
Native softether client for android and iOS

### ISSUE THREAD

**Issue by danyhm** [SoftEtherVPN/SoftEtherVPN#1663] opened 2022-09-24 07:05 UTC
Hello,

Regarding the latest protests in Iran , softether has been one of the few VPN protocols that is still working in Iran even with the heavy censorship. However there is no native android or iOS (free app) that supports the sofether protocol.
Other protocols supported for compatibility like openvpn or l2tp etc are all shutdown, however the softether protocol still works.

Please help the people and implemenr a native android iOS client

**Comment by domosekai** [comment] 2022-09-24 08:26
Duplicate of #1019 , #545

**Closed by domosekai** 2022-09-24 08:26 UTC
