### ISSUE TITLE
softether client keeps running in the background

### ISSUE THREAD

**Issue by paymanz** [SoftEtherVPN/SoftEtherVPN#1539] opened 2022-01-08 11:44 UTC
siftether vpn client keeps running in the background even if i set startup at windows login off it runs by itself!

can you solve this issue please?

**Comment by domosekai** [comment] 2022-01-08 15:48
SoftEther is a service so it starts automatically. You can manually stop it in Services. 
Duplicate of #288

**Closed** 2022-02-01 04:20 UTC
