### ISSUE TITLE
Feature Request: Static IP MAPPING (or best effort) for secure-DHCP

### ISSUE THREAD

**Issue by PaulGWebster** [SoftEtherVPN/SoftEtherVPN#783] opened 2018-10-29 14:18 UTC
It would be nice if there was a way to guarantee a client got a specific IP address or at least have the DHCP provided in SoftEther 'try' to give each client the ip it had last (likewise it should always try to hand out the one that has not been used for the longest time (or ever at all) for clients it has never seen before.

Without looking into the code to heavily I imagine 'last used ip' as a field on the user profiles?

For literally static mapping I assume something similier could be done with a list dialogue in the DHCP Settings, <username or MAC> | <IP>

**Comment by chipitsine** [comment] 2018-11-26 22:16
duplicate of https://github.com/SoftEtherVPN/SoftEtherVPN/issues/16

**Closed by chipitsine** 2018-11-26 22:16 UTC
Labels: feature
