### ISSUE TITLE
vpnserver stop on CentOS 6.5 hangs sometimes

### ISSUE THREAD

**Issue by ghost** [SoftEtherVPN/SoftEtherVPN#18] opened 2014-01-29 04:35 UTC
I've encountered a situation when stopping vpnserver and it would just hang. Logfile shows that it did shutdown (last line is: "The SoftEther VPN Server Engine has been successfully shutdown."). netstat -lntp shows vpnserver is not listening anymore.

But ps aux still shows the vpnserver process running:

/usr/vpnserver/vpnserver execsvc
/usr/vpnserver/vpnserver execsvc

which is causing my initscript to hang when stopping the service. Any way to debug more?

Starting vpnserver again will add 2 new processes in addition to the old ones remaining. Basically, vpnserver process sometimes doesn't disappear.

**Comment by adminport** [comment] 2017-08-14 16:43
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/341

New maintainer needed

**Comment by moatazelmasry2** [comment] 2017-11-21 21:29
@dnobori did you manage to implement a fix, or can you tell us at least what is the cause of the problem ?

**Comment by chipitsine** [comment] 2018-07-25 20:35
can we close this issue ?

**Closed** 2018-07-30 03:38 UTC
Labels: bug
