### ISSUE TITLE
Whether there is a way to custom mode/determine which mode will connect to the server ex:  VPN over ICMP / VPN over DNS functions

### ISSUE THREAD

**Issue by fdxreborn** [SoftEtherVPN/SoftEtherVPN#1481] opened 2021-09-13 20:24 UTC
Hi who's there!
Whether there is a way to custom mode/determine which mode will connect to the server, for example a VPN via ICMP/VPN over dns functionality is a great feature but we can only use this if the softether automatically decides so, 

for example even if https is allowed, but connecting via icmp or dns is a great advantage or option, so having the ability to choose it before softether decides is awesome. 

Secondly we found it difficult to test the feature because we had to block https and other traffic to "force" softether vpn to connect via vpn via icmp or dns, these two reasons (users can't specify) and users are forced to block connections to test it, is the reason why the powerful feature isn't used most of the time, even if it's a very good advantage.

**Comment by domosekai** [comment] 2023-03-01 16:51
Duplicate of #779

**Closed by domosekai** 2023-03-01 16:51 UTC
